/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Agent (void)
{
  GtkWidget *Agent;
  GtkWidget *fixedagent;
  GtkWidget *notebook;
  GtkWidget *fixedequipe;
  GtkWidget *entryidagentequipe;
  GtkWidget *entryidparkingformulaire;
  GtkWidget *entryroleequipe;
  GtkWidget *backgroundequipe;
  GtkWidget *buttonquitterequipe;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image24;
  GtkWidget *label101;
  GtkWidget *buttonsupprimer;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image32;
  GtkWidget *label114;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image33;
  GtkWidget *label115;
  GtkWidget *buttonajouter;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image34;
  GtkWidget *label116;
  GtkWidget *labelroleequipe;
  GtkWidget *buttonrechercheequipe;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image42;
  GtkWidget *label137;
  GtkWidget *buttonsavoirplus;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image43;
  GtkWidget *label138;
  GtkWidget *idparkingequipe;
  GtkWidget *idagentequipe;
  GtkWidget *scrolledtabequipe;
  GtkWidget *treeviewequipe;
  GtkWidget *tri;
  GtkWidget *combotri;
  GList *combotri_items = NULL;
  GtkWidget *combo_entrytri;
  GtkWidget *equipe;
  GtkWidget *fixedres;
  GtkWidget *backgroundres;
  GtkObject *spinbuttonanneeres_adj;
  GtkWidget *spinbuttonanneeres;
  GtkWidget *combojourres;
  GList *combojourres_items = NULL;
  GtkWidget *combo_entryjourres;
  GtkWidget *combomoisres;
  GList *combomoisres_items = NULL;
  GtkWidget *combo_entrymoisres;
  GtkWidget *buttonrechercheres;
  GtkWidget *image31;
  GtkWidget *buttonquitteres;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image21;
  GtkWidget *label96;
  GtkWidget *scrolledtabres;
  GtkWidget *treevieweres;
  GtkWidget *selectiondate;
  GtkWidget *res;

  Agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Agent, 1060, 663);
  gtk_window_set_title (GTK_WINDOW (Agent), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (Agent), FALSE);

  fixedagent = gtk_fixed_new ();
  gtk_widget_show (fixedagent);
  gtk_container_add (GTK_CONTAINER (Agent), fixedagent);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_fixed_put (GTK_FIXED (fixedagent), notebook, 0, 0);
  gtk_widget_set_size_request (notebook, 1060, 663);

  fixedequipe = gtk_fixed_new ();
  gtk_widget_show (fixedequipe);
  gtk_container_add (GTK_CONTAINER (notebook), fixedequipe);

  entryidagentequipe = gtk_entry_new ();
  gtk_widget_show (entryidagentequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), entryidagentequipe, 184, 32);
  gtk_widget_set_size_request (entryidagentequipe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidagentequipe), 8226);

  entryidparkingformulaire = gtk_entry_new ();
  gtk_widget_show (entryidparkingformulaire);
  gtk_fixed_put (GTK_FIXED (fixedequipe), entryidparkingformulaire, 184, 80);
  gtk_widget_set_size_request (entryidparkingformulaire, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidparkingformulaire), 8226);

  entryroleequipe = gtk_entry_new ();
  gtk_widget_show (entryroleequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), entryroleequipe, 440, 80);
  gtk_widget_set_size_request (entryroleequipe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryroleequipe), 8226);

  backgroundequipe = create_pixmap (Agent, "fotor-20241021152351.png");
  gtk_widget_show (backgroundequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), backgroundequipe, 0, 0);
  gtk_widget_set_size_request (backgroundequipe, 1060, 663);

  buttonquitterequipe = gtk_button_new ();
  gtk_widget_show (buttonquitterequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonquitterequipe, 927, 584);
  gtk_widget_set_size_request (buttonquitterequipe, 109, 35);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonquitterequipe), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox13), image24, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox13), label101, FALSE, FALSE, 0);

  buttonsupprimer = gtk_button_new ();
  gtk_widget_show (buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonsupprimer, 816, 584);
  gtk_widget_set_size_request (buttonsupprimer, 109, 35);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image32 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox17), image32, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox17), label114, FALSE, FALSE, 0);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonmodifier, 701, 584);
  gtk_widget_set_size_request (buttonmodifier, 109, 35);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image33 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox18), image33, FALSE, FALSE, 0);

  label115 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label115);
  gtk_box_pack_start (GTK_BOX (hbox18), label115, FALSE, FALSE, 0);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonajouter, 584, 584);
  gtk_widget_set_size_request (buttonajouter, 109, 35);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonajouter), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image34 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox19), image34, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox19), label116, FALSE, FALSE, 0);

  labelroleequipe = gtk_label_new (_("R\303\264le : "));
  gtk_widget_show (labelroleequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), labelroleequipe, 376, 85);
  gtk_widget_set_size_request (labelroleequipe, 57, 17);

  buttonrechercheequipe = gtk_button_new ();
  gtk_widget_show (buttonrechercheequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonrechercheequipe, 376, 32);
  gtk_widget_set_size_request (buttonrechercheequipe, 50, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (buttonrechercheequipe), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image42 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox26), image42, FALSE, FALSE, 0);

  label137 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label137);
  gtk_box_pack_start (GTK_BOX (hbox26), label137, FALSE, FALSE, 0);

  buttonsavoirplus = gtk_button_new ();
  gtk_widget_show (buttonsavoirplus);
  gtk_fixed_put (GTK_FIXED (fixedequipe), buttonsavoirplus, 448, 32);
  gtk_widget_set_size_request (buttonsavoirplus, 110, 29);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (buttonsavoirplus), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image43 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox27), image43, FALSE, FALSE, 0);

  label138 = gtk_label_new_with_mnemonic (_("savoir plus"));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (hbox27), label138, FALSE, FALSE, 0);

  idparkingequipe = gtk_label_new (_("ID-Parking : "));
  gtk_widget_show (idparkingequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), idparkingequipe, 72, 88);
  gtk_widget_set_size_request (idparkingequipe, 95, 17);

  idagentequipe = gtk_label_new (_("ID-Agent : "));
  gtk_widget_show (idagentequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), idagentequipe, 72, 40);
  gtk_widget_set_size_request (idagentequipe, 79, 17);

  scrolledtabequipe = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledtabequipe);
  gtk_fixed_put (GTK_FIXED (fixedequipe), scrolledtabequipe, 112, 184);
  gtk_widget_set_size_request (scrolledtabequipe, 760, 368);

  treeviewequipe = gtk_tree_view_new ();
  gtk_widget_show (treeviewequipe);
  gtk_container_add (GTK_CONTAINER (scrolledtabequipe), treeviewequipe);

  tri = gtk_label_new (_("Trier par : "));
  gtk_widget_show (tri);
  gtk_fixed_put (GTK_FIXED (fixedequipe), tri, 80, 144);
  gtk_widget_set_size_request (tri, 79, 17);

  combotri = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combotri)->popwin),
                     "GladeParentKey", combotri);
  gtk_widget_show (combotri);
  gtk_fixed_put (GTK_FIXED (fixedequipe), combotri, 184, 139);
  gtk_widget_set_size_request (combotri, 162, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combotri), TRUE);
  combotri_items = g_list_append (combotri_items, (gpointer) "");
  combotri_items = g_list_append (combotri_items, (gpointer) _("ID-Parking"));
  combotri_items = g_list_append (combotri_items, (gpointer) _("A....Z"));
  combotri_items = g_list_append (combotri_items, (gpointer) _("Z..A"));
  combotri_items = g_list_append (combotri_items, (gpointer) _("R\303\264le"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combotri), combotri_items);
  g_list_free (combotri_items);

  combo_entrytri = GTK_COMBO (combotri)->entry;
  gtk_widget_show (combo_entrytri);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entrytri), 8226);

  equipe = gtk_label_new (_("Equipe"));
  gtk_widget_show (equipe);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), equipe);
  gtk_widget_set_size_request (equipe, 63, -1);

  fixedres = gtk_fixed_new ();
  gtk_widget_show (fixedres);
  gtk_container_add (GTK_CONTAINER (notebook), fixedres);

  backgroundres = create_pixmap (Agent, "register.png");
  gtk_widget_show (backgroundres);
  gtk_fixed_put (GTK_FIXED (fixedres), backgroundres, 0, 0);
  gtk_widget_set_size_request (backgroundres, 1060, 663);

  spinbuttonanneeres_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonanneeres = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneeres_adj), 1, 0);
  gtk_widget_show (spinbuttonanneeres);
  gtk_fixed_put (GTK_FIXED (fixedres), spinbuttonanneeres, 536, 64);
  gtk_widget_set_size_request (spinbuttonanneeres, 72, 27);

  combojourres = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combojourres)->popwin),
                     "GladeParentKey", combojourres);
  gtk_widget_show (combojourres);
  gtk_fixed_put (GTK_FIXED (fixedres), combojourres, 336, 64);
  gtk_widget_set_size_request (combojourres, 66, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combojourres), TRUE);
  combojourres_items = g_list_append (combojourres_items, (gpointer) "");
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("1"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("2"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("3"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("4"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("6"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("7"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("8"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("9"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("10"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("11"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("12"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("13"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("14"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("15"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("16"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("17"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("18"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("19"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("20"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("21"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("22"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("23"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("24"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("25"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("26"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("27"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("28"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("29"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("30"));
  combojourres_items = g_list_append (combojourres_items, (gpointer) _("31"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combojourres), combojourres_items);
  g_list_free (combojourres_items);

  combo_entryjourres = GTK_COMBO (combojourres)->entry;
  gtk_widget_show (combo_entryjourres);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entryjourres), 8226);

  combomoisres = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combomoisres)->popwin),
                     "GladeParentKey", combomoisres);
  gtk_widget_show (combomoisres);
  gtk_fixed_put (GTK_FIXED (fixedres), combomoisres, 403, 64);
  gtk_widget_set_size_request (combomoisres, 131, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combomoisres), TRUE);
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) "");
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Janvier"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("F\303\251vrier"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Mars"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Avril"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Mai"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Juin"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Juillet"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Septembre"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Octobre"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("Novembre"));
  combomoisres_items = g_list_append (combomoisres_items, (gpointer) _("D\303\251cembre"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combomoisres), combomoisres_items);
  g_list_free (combomoisres_items);

  combo_entrymoisres = GTK_COMBO (combomoisres)->entry;
  gtk_widget_show (combo_entrymoisres);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entrymoisres), 8226);

  buttonrechercheres = gtk_button_new ();
  gtk_widget_show (buttonrechercheres);
  gtk_fixed_put (GTK_FIXED (fixedres), buttonrechercheres, 648, 61);
  gtk_widget_set_size_request (buttonrechercheres, 49, 30);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (buttonrechercheres), image31);
  gtk_widget_set_size_request (image31, 13, 16);

  buttonquitteres = gtk_button_new ();
  gtk_widget_show (buttonquitteres);
  gtk_fixed_put (GTK_FIXED (fixedres), buttonquitteres, 927, 584);
  gtk_widget_set_size_request (buttonquitteres, 109, 35);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonquitteres), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image21 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox12), image21, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox12), label96, FALSE, FALSE, 0);

  scrolledtabres = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledtabres);
  gtk_fixed_put (GTK_FIXED (fixedres), scrolledtabres, 96, 166);
  gtk_widget_set_size_request (scrolledtabres, 816, 420);

  treevieweres = gtk_tree_view_new ();
  gtk_widget_show (treevieweres);
  gtk_container_add (GTK_CONTAINER (scrolledtabres), treevieweres);

  selectiondate = gtk_label_new (_("S\303\251l\303\251ctionnez une date :"));
  gtk_widget_show (selectiondate);
  gtk_fixed_put (GTK_FIXED (fixedres), selectiondate, 152, 72);
  gtk_widget_set_size_request (selectiondate, 171, 17);

  res = gtk_label_new (_("R\303\251servations"));
  gtk_widget_show (res);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), res);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Agent, Agent, "Agent");
  GLADE_HOOKUP_OBJECT (Agent, fixedagent, "fixedagent");
  GLADE_HOOKUP_OBJECT (Agent, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (Agent, fixedequipe, "fixedequipe");
  GLADE_HOOKUP_OBJECT (Agent, entryidagentequipe, "entryidagentequipe");
  GLADE_HOOKUP_OBJECT (Agent, entryidparkingformulaire, "entryidparkingformulaire");
  GLADE_HOOKUP_OBJECT (Agent, entryroleequipe, "entryroleequipe");
  GLADE_HOOKUP_OBJECT (Agent, backgroundequipe, "backgroundequipe");
  GLADE_HOOKUP_OBJECT (Agent, buttonquitterequipe, "buttonquitterequipe");
  GLADE_HOOKUP_OBJECT (Agent, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Agent, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Agent, image24, "image24");
  GLADE_HOOKUP_OBJECT (Agent, label101, "label101");
  GLADE_HOOKUP_OBJECT (Agent, buttonsupprimer, "buttonsupprimer");
  GLADE_HOOKUP_OBJECT (Agent, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Agent, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Agent, image32, "image32");
  GLADE_HOOKUP_OBJECT (Agent, label114, "label114");
  GLADE_HOOKUP_OBJECT (Agent, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (Agent, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Agent, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Agent, image33, "image33");
  GLADE_HOOKUP_OBJECT (Agent, label115, "label115");
  GLADE_HOOKUP_OBJECT (Agent, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (Agent, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Agent, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Agent, image34, "image34");
  GLADE_HOOKUP_OBJECT (Agent, label116, "label116");
  GLADE_HOOKUP_OBJECT (Agent, labelroleequipe, "labelroleequipe");
  GLADE_HOOKUP_OBJECT (Agent, buttonrechercheequipe, "buttonrechercheequipe");
  GLADE_HOOKUP_OBJECT (Agent, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Agent, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (Agent, image42, "image42");
  GLADE_HOOKUP_OBJECT (Agent, label137, "label137");
  GLADE_HOOKUP_OBJECT (Agent, buttonsavoirplus, "buttonsavoirplus");
  GLADE_HOOKUP_OBJECT (Agent, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Agent, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (Agent, image43, "image43");
  GLADE_HOOKUP_OBJECT (Agent, label138, "label138");
  GLADE_HOOKUP_OBJECT (Agent, idparkingequipe, "idparkingequipe");
  GLADE_HOOKUP_OBJECT (Agent, idagentequipe, "idagentequipe");
  GLADE_HOOKUP_OBJECT (Agent, scrolledtabequipe, "scrolledtabequipe");
  GLADE_HOOKUP_OBJECT (Agent, treeviewequipe, "treeviewequipe");
  GLADE_HOOKUP_OBJECT (Agent, tri, "tri");
  GLADE_HOOKUP_OBJECT (Agent, combotri, "combotri");
  GLADE_HOOKUP_OBJECT (Agent, combo_entrytri, "combo_entrytri");
  GLADE_HOOKUP_OBJECT (Agent, equipe, "equipe");
  GLADE_HOOKUP_OBJECT (Agent, fixedres, "fixedres");
  GLADE_HOOKUP_OBJECT (Agent, backgroundres, "backgroundres");
  GLADE_HOOKUP_OBJECT (Agent, spinbuttonanneeres, "spinbuttonanneeres");
  GLADE_HOOKUP_OBJECT (Agent, combojourres, "combojourres");
  GLADE_HOOKUP_OBJECT (Agent, combo_entryjourres, "combo_entryjourres");
  GLADE_HOOKUP_OBJECT (Agent, combomoisres, "combomoisres");
  GLADE_HOOKUP_OBJECT (Agent, combo_entrymoisres, "combo_entrymoisres");
  GLADE_HOOKUP_OBJECT (Agent, buttonrechercheres, "buttonrechercheres");
  GLADE_HOOKUP_OBJECT (Agent, image31, "image31");
  GLADE_HOOKUP_OBJECT (Agent, buttonquitteres, "buttonquitteres");
  GLADE_HOOKUP_OBJECT (Agent, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Agent, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Agent, image21, "image21");
  GLADE_HOOKUP_OBJECT (Agent, label96, "label96");
  GLADE_HOOKUP_OBJECT (Agent, scrolledtabres, "scrolledtabres");
  GLADE_HOOKUP_OBJECT (Agent, treevieweres, "treevieweres");
  GLADE_HOOKUP_OBJECT (Agent, selectiondate, "selectiondate");
  GLADE_HOOKUP_OBJECT (Agent, res, "res");

  return Agent;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixednotifmodif;
  GtkWidget *notifmodif;
  GtkWidget *tickmodif;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier, 500, 100);
  gtk_window_set_resizable (GTK_WINDOW (modifier), FALSE);

  fixednotifmodif = gtk_fixed_new ();
  gtk_widget_show (fixednotifmodif);
  gtk_container_add (GTK_CONTAINER (modifier), fixednotifmodif);
  gtk_widget_set_size_request (fixednotifmodif, 334, 99);

  notifmodif = gtk_label_new (_("Agent modifi\303\251 avec succ\303\250s"));
  gtk_widget_show (notifmodif);
  gtk_fixed_put (GTK_FIXED (fixednotifmodif), notifmodif, 125, 38);
  gtk_widget_set_size_request (notifmodif, 202, 17);

  tickmodif = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (tickmodif);
  gtk_fixed_put (GTK_FIXED (fixednotifmodif), tickmodif, 320, 32);
  gtk_widget_set_size_request (tickmodif, 30, 26);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixednotifmodif, "fixednotifmodif");
  GLADE_HOOKUP_OBJECT (modifier, notifmodif, "notifmodif");
  GLADE_HOOKUP_OBJECT (modifier, tickmodif, "tickmodif");

  return modifier;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixedsupp;
  GtkWidget *supp;
  GtkWidget *cautionsup;
  GtkWidget *sursup;
  GtkWidget *buttonouisup;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label53;
  GtkWidget *buttonnonsup;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label54;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supprimer, 500, 176);
  gtk_window_set_resizable (GTK_WINDOW (supprimer), FALSE);

  fixedsupp = gtk_fixed_new ();
  gtk_widget_show (fixedsupp);
  gtk_container_add (GTK_CONTAINER (supprimer), fixedsupp);
  gtk_widget_set_size_request (fixedsupp, 342, 150);

  supp = gtk_label_new (_("Les donn\303\251es vont \303\252tre supprim\303\251es d\303\251finitivement"));
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixedsupp), supp, 56, 24);
  gtk_widget_set_size_request (supp, 356, 17);

  cautionsup = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (cautionsup);
  gtk_fixed_put (GTK_FIXED (fixedsupp), cautionsup, 416, 20);
  gtk_widget_set_size_request (cautionsup, 46, 23);

  sursup = gtk_label_new (_("\303\212tes-vous s\303\273r(e) ?"));
  gtk_widget_show (sursup);
  gtk_fixed_put (GTK_FIXED (fixedsupp), sursup, 176, 64);
  gtk_widget_set_size_request (sursup, 136, 17);
  gtk_misc_set_alignment (GTK_MISC (sursup), 0.47, 0.5);

  buttonouisup = gtk_button_new ();
  gtk_widget_show (buttonouisup);
  gtk_fixed_put (GTK_FIXED (fixedsupp), buttonouisup, 136, 104);
  gtk_widget_set_size_request (buttonouisup, 66, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonouisup), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox8), label53, FALSE, FALSE, 0);

  buttonnonsup = gtk_button_new ();
  gtk_widget_show (buttonnonsup);
  gtk_fixed_put (GTK_FIXED (fixedsupp), buttonnonsup, 294, 104);
  gtk_widget_set_size_request (buttonnonsup, 66, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonnonsup), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox9), label54, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixedsupp, "fixedsupp");
  GLADE_HOOKUP_OBJECT (supprimer, supp, "supp");
  GLADE_HOOKUP_OBJECT (supprimer, cautionsup, "cautionsup");
  GLADE_HOOKUP_OBJECT (supprimer, sursup, "sursup");
  GLADE_HOOKUP_OBJECT (supprimer, buttonouisup, "buttonouisup");
  GLADE_HOOKUP_OBJECT (supprimer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer, label53, "label53");
  GLADE_HOOKUP_OBJECT (supprimer, buttonnonsup, "buttonnonsup");
  GLADE_HOOKUP_OBJECT (supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (supprimer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (supprimer, image13, "image13");
  GLADE_HOOKUP_OBJECT (supprimer, label54, "label54");

  return supprimer;
}

GtkWidget*
create_notifsupp (void)
{
  GtkWidget *notifsupp;
  GtkWidget *fixednotifsupp;
  GtkWidget *ticksupp;
  GtkWidget *notifsupp;

  notifsupp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (notifsupp, 500, 100);
  gtk_window_set_resizable (GTK_WINDOW (notifsupp), FALSE);

  fixednotifsupp = gtk_fixed_new ();
  gtk_widget_show (fixednotifsupp);
  gtk_container_add (GTK_CONTAINER (notifsupp), fixednotifsupp);
  gtk_widget_set_size_request (fixednotifsupp, 500, -1);

  ticksupp = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ticksupp);
  gtk_fixed_put (GTK_FIXED (fixednotifsupp), ticksupp, 344, 29);
  gtk_widget_set_size_request (ticksupp, 34, 36);

  notifsupp = gtk_label_new (_("Agent supprim\303\251 avec succ\303\250s"));
  gtk_widget_show (notifsupp);
  gtk_fixed_put (GTK_FIXED (fixednotifsupp), notifsupp, 120, 40);
  gtk_widget_set_size_request (notifsupp, 222, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (notifsupp, notifsupp, "notifsupp");
  GLADE_HOOKUP_OBJECT (notifsupp, fixednotifsupp, "fixednotifsupp");
  GLADE_HOOKUP_OBJECT (notifsupp, ticksupp, "ticksupp");
  GLADE_HOOKUP_OBJECT (notifsupp, notifsupp, "notifsupp");

  return notifsupp;
}

GtkWidget*
create_filechooserdialog (void)
{
  GtkWidget *filechooserdialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *buttoncancelfile;
  GtkWidget *buttonopenfile;

  filechooserdialog = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog), 5);
  gtk_window_set_role (GTK_WINDOW (filechooserdialog), "GtkFileChooserDialog");
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  buttoncancelfile = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (buttoncancelfile);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), buttoncancelfile, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (buttoncancelfile, GTK_CAN_DEFAULT);

  buttonopenfile = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (buttonopenfile);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), buttonopenfile, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (buttonopenfile, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, filechooserdialog, "filechooserdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog, buttoncancelfile, "buttoncancelfile");
  GLADE_HOOKUP_OBJECT (filechooserdialog, buttonopenfile, "buttonopenfile");

  gtk_widget_grab_default (buttonopenfile);
  return filechooserdialog;
}

GtkWidget*
create_formulaire (void)
{
  GtkWidget *formulaire;
  GtkWidget *fixedformul;
  GtkWidget *entrynomformul;
  GtkWidget *entryprenomformul;
  GtkWidget *entryidagentformul;
  GtkWidget *entrynumtelformul;
  GtkWidget *entryadresseformul;
  GtkWidget *entryemailformul;
  GtkWidget *entryroleformul;
  GtkWidget *entryidparkingformul;
  GtkObject *spinbuttonanneformul_adj;
  GtkWidget *spinbuttonanneformul;
  GtkWidget *backgroundformul;
  GtkWidget *sexeformul;
  GtkWidget *buttonenregistrer;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image41;
  GtkWidget *label133;
  GtkWidget *radiobuttonhomme;
  GSList *radiobuttonhomme_group = NULL;
  GtkWidget *radiobuttonfemme;
  GtkWidget *nomformul;
  GtkWidget *entryexperience;
  GtkWidget *numtel;
  GtkWidget *roleformul;
  GtkWidget *emailformul;
  GtkWidget *adresseformul;
  GtkWidget *checkbuttonouiformul;
  GtkWidget *checkbuttonnonformul;
  GtkWidget *experience;
  GtkWidget *experimente;
  GtkWidget *prenomformul;
  GtkWidget *idagentformul;
  GtkWidget *combojourformul;
  GList *combojourformul_items = NULL;
  GtkWidget *entryjourfoemul;
  GtkWidget *combomoisformul;
  GList *combomoisformul_items = NULL;
  GtkWidget *entrymoisformul;
  GtkWidget *datenaissformul;
  GtkWidget *idparkingformul;
  GtkWidget *filechooserbuttonimage;
  GtkWidget *uploadimageformul;
  GtkWidget *buttonquitterformul;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image40;
  GtkWidget *label121;

  formulaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (formulaire, 1060, 663);
  gtk_window_set_title (GTK_WINDOW (formulaire), _("Formulaire Agent "));
  gtk_window_set_resizable (GTK_WINDOW (formulaire), FALSE);

  fixedformul = gtk_fixed_new ();
  gtk_widget_show (fixedformul);
  gtk_container_add (GTK_CONTAINER (formulaire), fixedformul);

  entrynomformul = gtk_entry_new ();
  gtk_widget_show (entrynomformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entrynomformul, 192, 40);
  gtk_widget_set_size_request (entrynomformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomformul), 8226);

  entryprenomformul = gtk_entry_new ();
  gtk_widget_show (entryprenomformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryprenomformul, 192, 95);
  gtk_widget_set_size_request (entryprenomformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomformul), 8226);

  entryidagentformul = gtk_entry_new ();
  gtk_widget_show (entryidagentformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryidagentformul, 192, 151);
  gtk_widget_set_size_request (entryidagentformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidagentformul), 8226);

  entrynumtelformul = gtk_entry_new ();
  gtk_widget_show (entrynumtelformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entrynumtelformul, 744, 40);
  gtk_widget_set_size_request (entrynumtelformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumtelformul), 8226);

  entryadresseformul = gtk_entry_new ();
  gtk_widget_show (entryadresseformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryadresseformul, 744, 96);
  gtk_widget_set_size_request (entryadresseformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresseformul), 8226);

  entryemailformul = gtk_entry_new ();
  gtk_widget_show (entryemailformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryemailformul, 744, 152);
  gtk_widget_set_size_request (entryemailformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemailformul), 8226);

  entryroleformul = gtk_entry_new ();
  gtk_widget_show (entryroleformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryroleformul, 744, 208);
  gtk_widget_set_size_request (entryroleformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryroleformul), 8226);

  entryidparkingformul = gtk_entry_new ();
  gtk_widget_show (entryidparkingformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryidparkingformul, 744, 272);
  gtk_widget_set_size_request (entryidparkingformul, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidparkingformul), 8226);

  spinbuttonanneformul_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonanneformul = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneformul_adj), 1, 0);
  gtk_widget_show (spinbuttonanneformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), spinbuttonanneformul, 368, 272);
  gtk_widget_set_size_request (spinbuttonanneformul, 71, 27);

  backgroundformul = create_pixmap (formulaire, "formilaure.png");
  gtk_widget_show (backgroundformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), backgroundformul, 0, 0);
  gtk_widget_set_size_request (backgroundformul, 1060, 663);

  sexeformul = gtk_label_new (_("Sexe :"));
  gtk_widget_show (sexeformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), sexeformul, 56, 216);
  gtk_widget_set_size_request (sexeformul, 49, 17);

  buttonenregistrer = gtk_button_new ();
  gtk_widget_show (buttonenregistrer);
  gtk_fixed_put (GTK_FIXED (fixedformul), buttonenregistrer, 800, 614);
  gtk_widget_set_size_request (buttonenregistrer, 109, 35);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonenregistrer), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image41 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox25), image41, FALSE, FALSE, 0);

  label133 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label133);
  gtk_box_pack_start (GTK_BOX (hbox25), label133, FALSE, FALSE, 0);

  radiobuttonhomme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonhomme);
  gtk_fixed_put (GTK_FIXED (fixedformul), radiobuttonhomme, 304, 206);
  gtk_widget_set_size_request (radiobuttonhomme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhomme), radiobuttonhomme_group);
  radiobuttonhomme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhomme));

  radiobuttonfemme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme "));
  gtk_widget_show (radiobuttonfemme);
  gtk_fixed_put (GTK_FIXED (fixedformul), radiobuttonfemme, 208, 206);
  gtk_widget_set_size_request (radiobuttonfemme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemme), radiobuttonhomme_group);
  radiobuttonhomme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemme));

  nomformul = gtk_label_new (_("Nom :"));
  gtk_widget_show (nomformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), nomformul, 48, 42);
  gtk_widget_set_size_request (nomformul, 49, 17);

  entryexperience = gtk_entry_new ();
  gtk_widget_show (entryexperience);
  gtk_fixed_put (GTK_FIXED (fixedformul), entryexperience, 536, 400);
  gtk_widget_set_size_request (entryexperience, 504, 187);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryexperience), 8226);

  numtel = gtk_label_new (_("N\302\260 de t\303\251l\303\251phone :"));
  gtk_widget_show (numtel);
  gtk_fixed_put (GTK_FIXED (fixedformul), numtel, 536, 40);
  gtk_widget_set_size_request (numtel, 121, 17);

  roleformul = gtk_label_new (_("R\303\264le :"));
  gtk_widget_show (roleformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), roleformul, 552, 208);
  gtk_widget_set_size_request (roleformul, 73, 25);

  emailformul = gtk_label_new (_("Email :"));
  gtk_widget_show (emailformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), emailformul, 552, 152);
  gtk_widget_set_size_request (emailformul, 72, 25);

  adresseformul = gtk_label_new (_("Adresse :"));
  gtk_widget_show (adresseformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), adresseformul, 552, 96);
  gtk_widget_set_size_request (adresseformul, 75, 17);

  checkbuttonouiformul = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkbuttonouiformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), checkbuttonouiformul, 744, 322);
  gtk_widget_set_size_request (checkbuttonouiformul, 56, 24);

  checkbuttonnonformul = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkbuttonnonformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), checkbuttonnonformul, 832, 322);
  gtk_widget_set_size_request (checkbuttonnonformul, 72, 24);

  experience = gtk_label_new (_("Exp\303\251rience : "));
  gtk_widget_show (experience);
  gtk_fixed_put (GTK_FIXED (fixedformul), experience, 503, 376);
  gtk_widget_set_size_request (experience, 156, 16);

  experimente = gtk_label_new (_("Exp\303\251riment\303\251 ? "));
  gtk_widget_show (experimente);
  gtk_fixed_put (GTK_FIXED (fixedformul), experimente, 533, 328);
  gtk_widget_set_size_request (experimente, 121, 17);

  prenomformul = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (prenomformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), prenomformul, 40, 96);
  gtk_widget_set_size_request (prenomformul, 69, 17);

  idagentformul = gtk_label_new (_("ID-Agent  :"));
  gtk_widget_show (idagentformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), idagentformul, 40, 159);
  gtk_widget_set_size_request (idagentformul, 89, 17);

  combojourformul = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combojourformul)->popwin),
                     "GladeParentKey", combojourformul);
  gtk_widget_show (combojourformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), combojourformul, 193, 272);
  gtk_widget_set_size_request (combojourformul, 71, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combojourformul), TRUE);
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) "");
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("1"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("2"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("3"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("4"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("6"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("7"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("8"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("9"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("10"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("11"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("12"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("13"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("14"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("15"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("16"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("17"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("18"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("19"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("20"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("21"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("22"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("23"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("24"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("25"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("26"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("27"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("28"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("29"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("30"));
  combojourformul_items = g_list_append (combojourformul_items, (gpointer) _("31"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combojourformul), combojourformul_items);
  g_list_free (combojourformul_items);

  entryjourfoemul = GTK_COMBO (combojourformul)->entry;
  gtk_widget_show (entryjourfoemul);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryjourfoemul), 8226);

  combomoisformul = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combomoisformul)->popwin),
                     "GladeParentKey", combomoisformul);
  gtk_widget_show (combomoisformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), combomoisformul, 264, 272);
  gtk_widget_set_size_request (combomoisformul, 110, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combomoisformul), TRUE);
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) "");
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Janvier"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("F\303\251vrier"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Mars"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Avril"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Mai"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Juin"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Juillet"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Septembre"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Octobre"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("Novembre"));
  combomoisformul_items = g_list_append (combomoisformul_items, (gpointer) _("D\303\251cembre"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combomoisformul), combomoisformul_items);
  g_list_free (combomoisformul_items);

  entrymoisformul = GTK_COMBO (combomoisformul)->entry;
  gtk_widget_show (entrymoisformul);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymoisformul), 8226);

  datenaissformul = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (datenaissformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), datenaissformul, 40, 277);
  gtk_widget_set_size_request (datenaissformul, 137, 17);

  idparkingformul = gtk_label_new (_("ID-Parking  :"));
  gtk_widget_show (idparkingformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), idparkingformul, 512, 276);
  gtk_widget_set_size_request (idparkingformul, 148, 17);

  filechooserbuttonimage = gtk_file_chooser_button_new (_("S\303\251lectionner un fichier"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbuttonimage);
  gtk_fixed_put (GTK_FIXED (fixedformul), filechooserbuttonimage, 232, 335);
  gtk_widget_set_size_request (filechooserbuttonimage, 160, 29);

  uploadimageformul = gtk_label_new (_("Uploadez votre photo  :"));
  gtk_widget_show (uploadimageformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), uploadimageformul, 40, 341);
  gtk_widget_set_size_request (uploadimageformul, 171, 17);

  buttonquitterformul = gtk_button_new ();
  gtk_widget_show (buttonquitterformul);
  gtk_fixed_put (GTK_FIXED (fixedformul), buttonquitterformul, 927, 614);
  gtk_widget_set_size_request (buttonquitterformul, 109, 35);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (buttonquitterformul), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image40 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox24), image40, FALSE, FALSE, 0);

  label121 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label121);
  gtk_box_pack_start (GTK_BOX (hbox24), label121, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (formulaire, formulaire, "formulaire");
  GLADE_HOOKUP_OBJECT (formulaire, fixedformul, "fixedformul");
  GLADE_HOOKUP_OBJECT (formulaire, entrynomformul, "entrynomformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryprenomformul, "entryprenomformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryidagentformul, "entryidagentformul");
  GLADE_HOOKUP_OBJECT (formulaire, entrynumtelformul, "entrynumtelformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryadresseformul, "entryadresseformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryemailformul, "entryemailformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryroleformul, "entryroleformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryidparkingformul, "entryidparkingformul");
  GLADE_HOOKUP_OBJECT (formulaire, spinbuttonanneformul, "spinbuttonanneformul");
  GLADE_HOOKUP_OBJECT (formulaire, backgroundformul, "backgroundformul");
  GLADE_HOOKUP_OBJECT (formulaire, sexeformul, "sexeformul");
  GLADE_HOOKUP_OBJECT (formulaire, buttonenregistrer, "buttonenregistrer");
  GLADE_HOOKUP_OBJECT (formulaire, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (formulaire, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (formulaire, image41, "image41");
  GLADE_HOOKUP_OBJECT (formulaire, label133, "label133");
  GLADE_HOOKUP_OBJECT (formulaire, radiobuttonhomme, "radiobuttonhomme");
  GLADE_HOOKUP_OBJECT (formulaire, radiobuttonfemme, "radiobuttonfemme");
  GLADE_HOOKUP_OBJECT (formulaire, nomformul, "nomformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryexperience, "entryexperience");
  GLADE_HOOKUP_OBJECT (formulaire, numtel, "numtel");
  GLADE_HOOKUP_OBJECT (formulaire, roleformul, "roleformul");
  GLADE_HOOKUP_OBJECT (formulaire, emailformul, "emailformul");
  GLADE_HOOKUP_OBJECT (formulaire, adresseformul, "adresseformul");
  GLADE_HOOKUP_OBJECT (formulaire, checkbuttonouiformul, "checkbuttonouiformul");
  GLADE_HOOKUP_OBJECT (formulaire, checkbuttonnonformul, "checkbuttonnonformul");
  GLADE_HOOKUP_OBJECT (formulaire, experience, "experience");
  GLADE_HOOKUP_OBJECT (formulaire, experimente, "experimente");
  GLADE_HOOKUP_OBJECT (formulaire, prenomformul, "prenomformul");
  GLADE_HOOKUP_OBJECT (formulaire, idagentformul, "idagentformul");
  GLADE_HOOKUP_OBJECT (formulaire, combojourformul, "combojourformul");
  GLADE_HOOKUP_OBJECT (formulaire, entryjourfoemul, "entryjourfoemul");
  GLADE_HOOKUP_OBJECT (formulaire, combomoisformul, "combomoisformul");
  GLADE_HOOKUP_OBJECT (formulaire, entrymoisformul, "entrymoisformul");
  GLADE_HOOKUP_OBJECT (formulaire, datenaissformul, "datenaissformul");
  GLADE_HOOKUP_OBJECT (formulaire, idparkingformul, "idparkingformul");
  GLADE_HOOKUP_OBJECT (formulaire, filechooserbuttonimage, "filechooserbuttonimage");
  GLADE_HOOKUP_OBJECT (formulaire, uploadimageformul, "uploadimageformul");
  GLADE_HOOKUP_OBJECT (formulaire, buttonquitterformul, "buttonquitterformul");
  GLADE_HOOKUP_OBJECT (formulaire, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (formulaire, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (formulaire, image40, "image40");
  GLADE_HOOKUP_OBJECT (formulaire, label121, "label121");

  return formulaire;
}

GtkWidget*
create_savoirplus_ (void)
{
  GtkWidget *savoirplus_;
  GtkWidget *fixedsavoirplus;
  GtkWidget *textviewexperience;
  GtkWidget *backgroundsavoirlpus;
  GtkWidget *experiencesaavoir;
  GtkWidget *nomsavoir;
  GtkWidget *prenomsavoir;
  GtkWidget *idparkingsavoir;
  GtkWidget *sexesavoir;
  GtkWidget *adressesavoir;
  GtkWidget *emailsavoir;
  GtkWidget *idparking;
  GtkWidget *idagent;
  GtkWidget *prenom;
  GtkWidget *nom;
  GtkWidget *adresse;
  GtkWidget *email;
  GtkWidget *sexe;
  GtkWidget *datenaiss;
  GtkWidget *experimentesavoir;
  GtkWidget *experimente;
  GtkWidget *idagentsavoir;
  GtkWidget *numtelsavoir;
  GtkWidget *rolesavoir;
  GtkWidget *numtel;
  GtkWidget *role;
  GtkWidget *datenaisssavoir;
  GtkWidget *image45;
  GtkWidget *buttonquittersavoirplus;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image47;
  GtkWidget *label167;

  savoirplus_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (savoirplus_, 900, 557);
  gtk_window_set_title (GTK_WINDOW (savoirplus_), _("window2"));
  gtk_window_set_resizable (GTK_WINDOW (savoirplus_), FALSE);

  fixedsavoirplus = gtk_fixed_new ();
  gtk_widget_show (fixedsavoirplus);
  gtk_container_add (GTK_CONTAINER (savoirplus_), fixedsavoirplus);

  textviewexperience = gtk_text_view_new ();
  gtk_widget_show (textviewexperience);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), textviewexperience, 120, 296);
  gtk_widget_set_size_request (textviewexperience, 688, 193);

  backgroundsavoirlpus = create_pixmap (savoirplus_, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (backgroundsavoirlpus);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), backgroundsavoirlpus, 0, 0);
  gtk_widget_set_size_request (backgroundsavoirlpus, 900, 557);

  experiencesaavoir = gtk_label_new (_("Experience : "));
  gtk_widget_show (experiencesaavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), experiencesaavoir, 96, 272);
  gtk_widget_set_size_request (experiencesaavoir, 123, 17);

  nomsavoir = gtk_label_new (_("Nom : "));
  gtk_widget_show (nomsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), nomsavoir, 264, 32);
  gtk_widget_set_size_request (nomsavoir, 57, 17);

  prenomsavoir = gtk_label_new (_("Pr\303\251nom : "));
  gtk_widget_show (prenomsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), prenomsavoir, 264, 80);
  gtk_widget_set_size_request (prenomsavoir, 78, 17);

  idparkingsavoir = gtk_label_new (_("ID-Parking :"));
  gtk_widget_show (idparkingsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), idparkingsavoir, 264, 160);
  gtk_widget_set_size_request (idparkingsavoir, 103, 17);

  sexesavoir = gtk_label_new (_("Sexe : "));
  gtk_widget_show (sexesavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), sexesavoir, 544, 120);
  gtk_widget_set_size_request (sexesavoir, 57, 17);

  adressesavoir = gtk_label_new (_("Adresse: "));
  gtk_widget_show (adressesavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), adressesavoir, 528, 80);
  gtk_widget_set_size_request (adressesavoir, 86, 17);

  emailsavoir = gtk_label_new (_("E-mail : "));
  gtk_widget_show (emailsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), emailsavoir, 536, 32);
  gtk_widget_set_size_request (emailsavoir, 73, 17);

  idparking = gtk_label_new (_("...."));
  gtk_widget_show (idparking);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), idparking, 352, 160);
  gtk_widget_set_size_request (idparking, 89, 16);

  idagent = gtk_label_new (_("...."));
  gtk_widget_show (idagent);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), idagent, 368, 120);
  gtk_widget_set_size_request (idagent, 61, 17);

  prenom = gtk_label_new (_("...."));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), prenom, 368, 80);
  gtk_widget_set_size_request (prenom, 57, 17);

  nom = gtk_label_new (_("...."));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), nom, 368, 24);
  gtk_widget_set_size_request (nom, 57, 17);

  adresse = gtk_label_new (_("...."));
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), adresse, 664, 80);
  gtk_widget_set_size_request (adresse, 96, 17);

  email = gtk_label_new (_("...."));
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), email, 664, 32);
  gtk_widget_set_size_request (email, 94, 17);

  sexe = gtk_label_new (_("...."));
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), sexe, 672, 112);
  gtk_widget_set_size_request (sexe, 71, 17);

  datenaiss = gtk_label_new (_("...."));
  gtk_widget_show (datenaiss);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), datenaiss, 416, 200);
  gtk_widget_set_size_request (datenaiss, 105, 17);

  experimentesavoir = gtk_label_new (_("Exp\303\251riment\303\251 ? "));
  gtk_widget_show (experimentesavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), experimentesavoir, 96, 240);
  gtk_widget_set_size_request (experimentesavoir, 129, 17);

  experimente = gtk_label_new (_("...."));
  gtk_widget_show (experimente);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), experimente, 232, 240);
  gtk_widget_set_size_request (experimente, 57, 17);

  idagentsavoir = gtk_label_new (_("ID-Agnet : "));
  gtk_widget_show (idagentsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), idagentsavoir, 256, 120);
  gtk_widget_set_size_request (idagentsavoir, 115, 17);

  numtelsavoir = gtk_label_new (_("N\302\260 de t\303\251l\303\251phone : "));
  gtk_widget_show (numtelsavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), numtelsavoir, 528, 200);
  gtk_widget_set_size_request (numtelsavoir, 138, 17);

  rolesavoir = gtk_label_new (_("R\303\264le : "));
  gtk_widget_show (rolesavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), rolesavoir, 544, 160);
  gtk_widget_set_size_request (rolesavoir, 57, 17);

  numtel = gtk_label_new (_("...."));
  gtk_widget_show (numtel);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), numtel, 680, 200);
  gtk_widget_set_size_request (numtel, 57, 17);

  role = gtk_label_new (_("...."));
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), role, 656, 160);
  gtk_widget_set_size_request (role, 95, 17);

  datenaisssavoir = gtk_label_new (_("Date De Naissance : "));
  gtk_widget_show (datenaisssavoir);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), datenaisssavoir, 256, 200);
  gtk_widget_set_size_request (datenaisssavoir, 163, 17);

  image45 = create_pixmap (savoirplus_, "man-icon-vector-260nw-1040084344.jpg");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), image45, 32, 32);
  gtk_widget_set_size_request (image45, 200, 183);

  buttonquittersavoirplus = gtk_button_new ();
  gtk_widget_show (buttonquittersavoirplus);
  gtk_fixed_put (GTK_FIXED (fixedsavoirplus), buttonquittersavoirplus, 777, 517);
  gtk_widget_set_size_request (buttonquittersavoirplus, 109, 35);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (buttonquittersavoirplus), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image47 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_box_pack_start (GTK_BOX (hbox28), image47, FALSE, FALSE, 0);

  label167 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (hbox28), label167, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (savoirplus_, savoirplus_, "savoirplus_");
  GLADE_HOOKUP_OBJECT (savoirplus_, fixedsavoirplus, "fixedsavoirplus");
  GLADE_HOOKUP_OBJECT (savoirplus_, textviewexperience, "textviewexperience");
  GLADE_HOOKUP_OBJECT (savoirplus_, backgroundsavoirlpus, "backgroundsavoirlpus");
  GLADE_HOOKUP_OBJECT (savoirplus_, experiencesaavoir, "experiencesaavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, nomsavoir, "nomsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, prenomsavoir, "prenomsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, idparkingsavoir, "idparkingsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, sexesavoir, "sexesavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, adressesavoir, "adressesavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, emailsavoir, "emailsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, idparking, "idparking");
  GLADE_HOOKUP_OBJECT (savoirplus_, idagent, "idagent");
  GLADE_HOOKUP_OBJECT (savoirplus_, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (savoirplus_, nom, "nom");
  GLADE_HOOKUP_OBJECT (savoirplus_, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (savoirplus_, email, "email");
  GLADE_HOOKUP_OBJECT (savoirplus_, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (savoirplus_, datenaiss, "datenaiss");
  GLADE_HOOKUP_OBJECT (savoirplus_, experimentesavoir, "experimentesavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, experimente, "experimente");
  GLADE_HOOKUP_OBJECT (savoirplus_, idagentsavoir, "idagentsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, numtelsavoir, "numtelsavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, rolesavoir, "rolesavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, numtel, "numtel");
  GLADE_HOOKUP_OBJECT (savoirplus_, role, "role");
  GLADE_HOOKUP_OBJECT (savoirplus_, datenaisssavoir, "datenaisssavoir");
  GLADE_HOOKUP_OBJECT (savoirplus_, image45, "image45");
  GLADE_HOOKUP_OBJECT (savoirplus_, buttonquittersavoirplus, "buttonquittersavoirplus");
  GLADE_HOOKUP_OBJECT (savoirplus_, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (savoirplus_, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (savoirplus_, image47, "image47");
  GLADE_HOOKUP_OBJECT (savoirplus_, label167, "label167");

  return savoirplus_;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixedajouter;
  GtkWidget *tickajout;
  GtkWidget *notifajout;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajouter, 500, 100);
  gtk_window_set_resizable (GTK_WINDOW (ajouter), FALSE);

  fixedajouter = gtk_fixed_new ();
  gtk_widget_show (fixedajouter);
  gtk_container_add (GTK_CONTAINER (ajouter), fixedajouter);

  tickajout = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (tickajout);
  gtk_fixed_put (GTK_FIXED (fixedajouter), tickajout, 320, 40);
  gtk_widget_set_size_request (tickajout, 32, 16);

  notifajout = gtk_label_new (_("Agent ajout\303\251 avec succ\303\250s"));
  gtk_widget_show (notifajout);
  gtk_fixed_put (GTK_FIXED (fixedajouter), notifajout, 128, 40);
  gtk_widget_set_size_request (notifajout, 208, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixedajouter, "fixedajouter");
  GLADE_HOOKUP_OBJECT (ajouter, tickajout, "tickajout");
  GLADE_HOOKUP_OBJECT (ajouter, notifajout, "notifajout");

  return ajouter;
}

