/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Agent (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_notifsupp (void);
GtkWidget* create_filechooserdialog (void);
GtkWidget* create_formulaire (void);
GtkWidget* create_savoirplus_ (void);
GtkWidget* create_ajouter (void);
