/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Agent;
  GtkWidget *modifier;
  GtkWidget *supprimer;
  GtkWidget *notifsupp;
  GtkWidget *filechooserdialog;
  GtkWidget *formulaire;
  GtkWidget *savoirplus_;
  GtkWidget *ajouter;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Agent = create_Agent ();
  gtk_widget_show (Agent);
  modifier = create_modifier ();
  gtk_widget_show (modifier);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  notifsupp = create_notifsupp ();
  gtk_widget_show (notifsupp);
  filechooserdialog = create_filechooserdialog ();
  gtk_widget_show (filechooserdialog);
  formulaire = create_formulaire ();
  gtk_widget_show (formulaire);
  savoirplus_ = create_savoirplus_ ();
  gtk_widget_show (savoirplus_);
  ajouter = create_ajouter ();
  gtk_widget_show (ajouter);

  gtk_main ();
  return 0;
}

