/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ARE_U_SURE_MODIF (void)
{
  GtkWidget *ARE_U_SURE_MODIF;
  GtkWidget *fixed6;
  GtkWidget *button20;
  GtkWidget *image16;
  GtkWidget *label27;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label75;
  GtkWidget *button10;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label72;

  ARE_U_SURE_MODIF = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ARE_U_SURE_MODIF, 500, 200);
  gtk_window_set_title (GTK_WINDOW (ARE_U_SURE_MODIF), _("window4"));
  gtk_window_set_resizable (GTK_WINDOW (ARE_U_SURE_MODIF), FALSE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ARE_U_SURE_MODIF), fixed6);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed6), button20, 450, 16);
  gtk_widget_set_size_request (button20, 32, 32);

  image16 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (button20), image16);

  label27 = gtk_label_new (_("\303\212TES-VOUS S\303\233R DE VOULOIR ENREGISTRER LES MODIFICATIONS?"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 0, 56);
  gtk_widget_set_size_request (label27, 500, 40);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 280, 120);
  gtk_widget_set_size_request (button11, 109, 35);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("OUI"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox10), label75, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 104, 120);
  gtk_widget_set_size_request (button10, 109, 35);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button10), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("NON"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox7), label72, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ARE_U_SURE_MODIF, ARE_U_SURE_MODIF, "ARE_U_SURE_MODIF");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, button20, "button20");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, image16, "image16");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, label27, "label27");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, button11, "button11");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, image14, "image14");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, label75, "label75");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, button10, "button10");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, image11, "image11");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_MODIF, label72, "label72");

  return ARE_U_SURE_MODIF;
}

GtkWidget*
create_ARE_U_SURE_DEL (void)
{
  GtkWidget *ARE_U_SURE_DEL;
  GtkWidget *fixed7;
  GtkWidget *button19;
  GtkWidget *image15;
  GtkWidget *label28;
  GtkWidget *button13;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label74;
  GtkWidget *button12;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label73;

  ARE_U_SURE_DEL = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ARE_U_SURE_DEL, 500, 200);
  gtk_window_set_title (GTK_WINDOW (ARE_U_SURE_DEL), _("window4"));
  gtk_window_set_resizable (GTK_WINDOW (ARE_U_SURE_DEL), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ARE_U_SURE_DEL), fixed7);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed7), button19, 448, 16);
  gtk_widget_set_size_request (button19, 32, 32);

  image15 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (button19), image15);

  label28 = gtk_label_new (_("\303\212TES-VOUS S\303\233R DE SUPPRIMER CETTE R\303\211SERVATION ?"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed7), label28, 8, 32);
  gtk_widget_set_size_request (label28, 464, 72);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed7), button13, 296, 112);
  gtk_widget_set_size_request (button13, 109, 35);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button13), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("OUI"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox9), label74, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed7), button12, 88, 112);
  gtk_widget_set_size_request (button12, 109, 35);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button12), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("NON"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox8), label73, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ARE_U_SURE_DEL, ARE_U_SURE_DEL, "ARE_U_SURE_DEL");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, button19, "button19");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, image15, "image15");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, label28, "label28");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, button13, "button13");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, image13, "image13");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, label74, "label74");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, button12, "button12");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, image12, "image12");
  GLADE_HOOKUP_OBJECT (ARE_U_SURE_DEL, label73, "label73");

  return ARE_U_SURE_DEL;
}

GtkWidget*
create_COMBO (void)
{
  GtkWidget *COMBO;
  GtkWidget *notebook1;
  GtkWidget *fixed11;
  GtkWidget *clist1;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *image28;
  GtkWidget *button54;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image25;
  GtkWidget *label91;
  GtkWidget *button55;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image26;
  GtkWidget *label92;
  GtkWidget *button56;
  GtkWidget *image27;
  GtkWidget *button52;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image23;
  GtkWidget *label89;
  GtkWidget *label49;
  GtkWidget *fixed13;
  GtkWidget *entry29;
  GtkWidget *entry30;
  GtkWidget *entry32;
  GtkWidget *entry33;
  GtkWidget *entry34;
  GtkWidget *entry35;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *image29;
  GtkWidget *button47;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label69;
  GtkWidget *button44;
  GtkWidget *image9;
  GtkWidget *button46;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label70;
  GtkWidget *button45;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label71;
  GtkWidget *label55;
  GtkWidget *label59;
  GtkWidget *label54;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *label58;
  GtkWidget *label57;
  GtkWidget *label56;
  GtkWidget *label51;
  GtkWidget *fixed14;
  GtkWidget *entry38;
  GtkWidget *entry39;
  GtkWidget *entry40;
  GtkWidget *entry41;
  GtkWidget *entry42;
  GtkWidget *entry43;
  GtkWidget *entry44;
  GtkWidget *entry45;
  GtkWidget *image30;
  GtkWidget *button48;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label83;
  GtkWidget *button49;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image22;
  GtkWidget *label88;
  GtkWidget *button50;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image20;
  GtkWidget *label87;
  GtkWidget *button51;
  GtkWidget *image21;
  GtkWidget *label80;
  GtkWidget *label78;
  GtkWidget *label77;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *label79;
  GtkWidget *label76;

  COMBO = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (COMBO, 1060, 663);
  gtk_window_set_title (GTK_WINDOW (COMBO), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (COMBO), FALSE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (COMBO), notebook1);
  gtk_widget_set_size_request (notebook1, 1064, 625);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);
  gtk_widget_set_size_request (fixed11, 1060, 663);

  clist1 = gtk_clist_new (9);
  gtk_widget_show (clist1);
  gtk_fixed_put (GTK_FIXED (fixed11), clist1, 40, 16);
  gtk_widget_set_size_request (clist1, 784, 288);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 6, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 7, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 8, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label101 = gtk_label_new (_("ID-REV"));
  gtk_widget_show (label101);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label101);

  label102 = gtk_label_new (_("CIN"));
  gtk_widget_show (label102);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label102);

  label103 = gtk_label_new (_("NOM"));
  gtk_widget_show (label103);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label103);

  label104 = gtk_label_new (_("PR\303\211NOM"));
  gtk_widget_show (label104);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label104);

  label105 = gtk_label_new (_("D/H"));
  gtk_widget_show (label105);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label105);

  label106 = gtk_label_new (_("DUR\303\211\303\211"));
  gtk_widget_show (label106);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, label106);

  label107 = gtk_label_new (_("ID-VEH"));
  gtk_widget_show (label107);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 6, label107);

  label108 = gtk_label_new (_("PHONE"));
  gtk_widget_show (label108);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 7, label108);

  label109 = gtk_label_new (_("SECTION"));
  gtk_widget_show (label109);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 8, label109);

  image28 = create_pixmap (COMBO, "fotor-20241018225050.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed11), image28, 0, 0);
  gtk_widget_set_size_request (image28, 1060, 663);

  button54 = gtk_button_new ();
  gtk_widget_show (button54);
  gtk_fixed_put (GTK_FIXED (fixed11), button54, 848, 416);
  gtk_widget_set_size_request (button54, 184, 56);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button54), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image25 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox17), image25, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("RETIRER\nLA R\303\211SRVATION"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox17), label91, FALSE, FALSE, 0);

  button55 = gtk_button_new ();
  gtk_widget_show (button55);
  gtk_fixed_put (GTK_FIXED (fixed11), button55, 848, 304);
  gtk_widget_set_size_request (button55, 184, 64);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button55), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image26 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox18), image26, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("MODIFIER\nLA R\303\211SERVATION"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox18), label92, FALSE, FALSE, 0);

  button56 = gtk_button_new ();
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed11), button56, 1000, 16);
  gtk_widget_set_size_request (button56, 32, 32);

  image27 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (button56), image27);

  button52 = gtk_button_new ();
  gtk_widget_show (button52);
  gtk_fixed_put (GTK_FIXED (fixed11), button52, 852, 152);
  gtk_widget_set_size_request (button52, 184, 64);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button52), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image23 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox15), image23, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("R\303\211CLAMATION"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox15), label89, FALSE, FALSE, 0);

  label49 = gtk_label_new (_("MES R\303\211SERVATIONS"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label49);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed13), entry29, 256, 248);
  gtk_widget_set_size_request (entry29, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed13), entry30, 256, 176);
  gtk_widget_set_size_request (entry30, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed13), entry32, 256, 536);
  gtk_widget_set_size_request (entry32, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  entry33 = gtk_entry_new ();
  gtk_widget_show (entry33);
  gtk_fixed_put (GTK_FIXED (fixed13), entry33, 256, 464);
  gtk_widget_set_size_request (entry33, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 8226);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed13), entry34, 256, 96);
  gtk_widget_set_size_request (entry34, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  entry35 = gtk_entry_new ();
  gtk_widget_show (entry35);
  gtk_fixed_put (GTK_FIXED (fixed13), entry35, 256, 24);
  gtk_widget_set_size_request (entry35, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry35), 8226);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed13), entry36, 256, 392);
  gtk_widget_set_size_request (entry36, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed13), entry37, 256, 320);
  gtk_widget_set_size_request (entry37, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  image29 = create_pixmap (COMBO, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed13), image29, 0, 0);
  gtk_widget_set_size_request (image29, 1060, 663);

  button47 = gtk_button_new ();
  gtk_widget_show (button47);
  gtk_fixed_put (GTK_FIXED (fixed13), button47, 768, 56);
  gtk_widget_set_size_request (button47, 192, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button47), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("R\303\211CLAMATION"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox4), label69, FALSE, FALSE, 0);

  button44 = gtk_button_new ();
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed13), button44, 1000, 16);
  gtk_widget_set_size_request (button44, 32, 32);

  image9 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button44), image9);

  button46 = gtk_button_new ();
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed13), button46, 760, 384);
  gtk_widget_set_size_request (button46, 190, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button46), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("RETOUR"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox5), label70, FALSE, FALSE, 0);

  button45 = gtk_button_new ();
  gtk_widget_show (button45);
  gtk_fixed_put (GTK_FIXED (fixed13), button45, 760, 488);
  gtk_widget_set_size_request (button45, 190, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button45), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox6), label71, FALSE, FALSE, 0);

  label55 = gtk_label_new (_("EMPLACEMENT/ SECTION :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed13), label55, 48, 520);
  gtk_widget_set_size_request (label55, 208, 72);

  label59 = gtk_label_new (_("NUM\303\211RO\nDE T\303\211L\303\211PHONE :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed13), label59, 48, 456);
  gtk_widget_set_size_request (label59, 200, 64);

  label54 = gtk_label_new (_("NUM\303\211RO\nDE LA V\303\211HICULES :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed13), label54, 48, 376);
  gtk_widget_set_size_request (label54, 200, 64);

  label53 = gtk_label_new (_("DUR\303\211E :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed13), label53, 48, 312);
  gtk_widget_set_size_request (label53, 200, 64);

  label52 = gtk_label_new (_("DATE ET HEURE :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed13), label52, 48, 240);
  gtk_widget_set_size_request (label52, 200, 64);

  label58 = gtk_label_new (_("PR\303\211NOM :"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed13), label58, 48, 168);
  gtk_widget_set_size_request (label58, 200, 64);

  label57 = gtk_label_new (_("NOM :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed13), label57, 48, 88);
  gtk_widget_set_size_request (label57, 192, 64);

  label56 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed13), label56, 48, 24);
  gtk_widget_set_size_request (label56, 192, 48);

  label51 = gtk_label_new (_("AJOUTER\nUNE R\303\211SERVATION"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label51);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed14);

  entry38 = gtk_entry_new ();
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed14), entry38, 256, 248);
  gtk_widget_set_size_request (entry38, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed14), entry39, 256, 176);
  gtk_widget_set_size_request (entry39, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed14), entry40, 256, 536);
  gtk_widget_set_size_request (entry40, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  entry41 = gtk_entry_new ();
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed14), entry41, 256, 464);
  gtk_widget_set_size_request (entry41, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  entry42 = gtk_entry_new ();
  gtk_widget_show (entry42);
  gtk_fixed_put (GTK_FIXED (fixed14), entry42, 256, 96);
  gtk_widget_set_size_request (entry42, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  entry43 = gtk_entry_new ();
  gtk_widget_show (entry43);
  gtk_fixed_put (GTK_FIXED (fixed14), entry43, 256, 24);
  gtk_widget_set_size_request (entry43, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry43), 8226);

  entry44 = gtk_entry_new ();
  gtk_widget_show (entry44);
  gtk_fixed_put (GTK_FIXED (fixed14), entry44, 256, 392);
  gtk_widget_set_size_request (entry44, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry44), 8226);

  entry45 = gtk_entry_new ();
  gtk_widget_show (entry45);
  gtk_fixed_put (GTK_FIXED (fixed14), entry45, 256, 320);
  gtk_widget_set_size_request (entry45, 244, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  image30 = create_pixmap (COMBO, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed14), image30, 0, 0);
  gtk_widget_set_size_request (image30, 1060, 663);

  button48 = gtk_button_new ();
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed14), button48, 768, 56);
  gtk_widget_set_size_request (button48, 192, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button48), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("R\303\211CLAMATION"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox11), label83, FALSE, FALSE, 0);

  button49 = gtk_button_new ();
  gtk_widget_show (button49);
  gtk_fixed_put (GTK_FIXED (fixed14), button49, 760, 384);
  gtk_widget_set_size_request (button49, 190, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button49), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image22 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox14), image22, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("ANNULER"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox14), label88, FALSE, FALSE, 0);

  button50 = gtk_button_new ();
  gtk_widget_show (button50);
  gtk_fixed_put (GTK_FIXED (fixed14), button50, 760, 488);
  gtk_widget_set_size_request (button50, 190, 56);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button50), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image20 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox13), image20, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox13), label87, FALSE, FALSE, 0);

  button51 = gtk_button_new ();
  gtk_widget_show (button51);
  gtk_fixed_put (GTK_FIXED (fixed14), button51, 1000, 16);
  gtk_widget_set_size_request (button51, 32, 32);

  image21 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (button51), image21);

  label80 = gtk_label_new (_("PR\303\211NOM :"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed14), label80, 48, 168);
  gtk_widget_set_size_request (label80, 200, 64);

  label78 = gtk_label_new (_("NOM :"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed14), label78, 48, 88);
  gtk_widget_set_size_request (label78, 192, 64);

  label77 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed14), label77, 48, 24);
  gtk_widget_set_size_request (label77, 192, 48);

  label81 = gtk_label_new (_("DATE ET HEURE :"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed14), label81, 48, 240);
  gtk_widget_set_size_request (label81, 200, 64);

  label82 = gtk_label_new (_("DUR\303\211E :"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed14), label82, 48, 312);
  gtk_widget_set_size_request (label82, 200, 64);

  label84 = gtk_label_new (_("NUM\303\211RO\nDE LA V\303\211HICULES :"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed14), label84, 48, 376);
  gtk_widget_set_size_request (label84, 200, 64);

  label85 = gtk_label_new (_("NUM\303\211RO\nDE T\303\211L\303\211PHONE :"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed14), label85, 48, 456);
  gtk_widget_set_size_request (label85, 200, 64);

  label79 = gtk_label_new (_("EMPLACEMENT/ SECTION :"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed14), label79, 48, 520);
  gtk_widget_set_size_request (label79, 208, 72);

  label76 = gtk_label_new (_("MODIFIER\nUNE R\303\211SERVATION"));
  gtk_widget_show (label76);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label76);
  gtk_widget_set_size_request (label76, 126, 31);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (COMBO, COMBO, "COMBO");
  GLADE_HOOKUP_OBJECT (COMBO, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (COMBO, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (COMBO, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (COMBO, label101, "label101");
  GLADE_HOOKUP_OBJECT (COMBO, label102, "label102");
  GLADE_HOOKUP_OBJECT (COMBO, label103, "label103");
  GLADE_HOOKUP_OBJECT (COMBO, label104, "label104");
  GLADE_HOOKUP_OBJECT (COMBO, label105, "label105");
  GLADE_HOOKUP_OBJECT (COMBO, label106, "label106");
  GLADE_HOOKUP_OBJECT (COMBO, label107, "label107");
  GLADE_HOOKUP_OBJECT (COMBO, label108, "label108");
  GLADE_HOOKUP_OBJECT (COMBO, label109, "label109");
  GLADE_HOOKUP_OBJECT (COMBO, image28, "image28");
  GLADE_HOOKUP_OBJECT (COMBO, button54, "button54");
  GLADE_HOOKUP_OBJECT (COMBO, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (COMBO, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (COMBO, image25, "image25");
  GLADE_HOOKUP_OBJECT (COMBO, label91, "label91");
  GLADE_HOOKUP_OBJECT (COMBO, button55, "button55");
  GLADE_HOOKUP_OBJECT (COMBO, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (COMBO, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (COMBO, image26, "image26");
  GLADE_HOOKUP_OBJECT (COMBO, label92, "label92");
  GLADE_HOOKUP_OBJECT (COMBO, button56, "button56");
  GLADE_HOOKUP_OBJECT (COMBO, image27, "image27");
  GLADE_HOOKUP_OBJECT (COMBO, button52, "button52");
  GLADE_HOOKUP_OBJECT (COMBO, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (COMBO, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (COMBO, image23, "image23");
  GLADE_HOOKUP_OBJECT (COMBO, label89, "label89");
  GLADE_HOOKUP_OBJECT (COMBO, label49, "label49");
  GLADE_HOOKUP_OBJECT (COMBO, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (COMBO, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (COMBO, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (COMBO, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (COMBO, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (COMBO, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (COMBO, entry35, "entry35");
  GLADE_HOOKUP_OBJECT (COMBO, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (COMBO, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (COMBO, image29, "image29");
  GLADE_HOOKUP_OBJECT (COMBO, button47, "button47");
  GLADE_HOOKUP_OBJECT (COMBO, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (COMBO, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (COMBO, image6, "image6");
  GLADE_HOOKUP_OBJECT (COMBO, label69, "label69");
  GLADE_HOOKUP_OBJECT (COMBO, button44, "button44");
  GLADE_HOOKUP_OBJECT (COMBO, image9, "image9");
  GLADE_HOOKUP_OBJECT (COMBO, button46, "button46");
  GLADE_HOOKUP_OBJECT (COMBO, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (COMBO, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (COMBO, image7, "image7");
  GLADE_HOOKUP_OBJECT (COMBO, label70, "label70");
  GLADE_HOOKUP_OBJECT (COMBO, button45, "button45");
  GLADE_HOOKUP_OBJECT (COMBO, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (COMBO, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (COMBO, image8, "image8");
  GLADE_HOOKUP_OBJECT (COMBO, label71, "label71");
  GLADE_HOOKUP_OBJECT (COMBO, label55, "label55");
  GLADE_HOOKUP_OBJECT (COMBO, label59, "label59");
  GLADE_HOOKUP_OBJECT (COMBO, label54, "label54");
  GLADE_HOOKUP_OBJECT (COMBO, label53, "label53");
  GLADE_HOOKUP_OBJECT (COMBO, label52, "label52");
  GLADE_HOOKUP_OBJECT (COMBO, label58, "label58");
  GLADE_HOOKUP_OBJECT (COMBO, label57, "label57");
  GLADE_HOOKUP_OBJECT (COMBO, label56, "label56");
  GLADE_HOOKUP_OBJECT (COMBO, label51, "label51");
  GLADE_HOOKUP_OBJECT (COMBO, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (COMBO, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (COMBO, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (COMBO, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (COMBO, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (COMBO, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (COMBO, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (COMBO, entry44, "entry44");
  GLADE_HOOKUP_OBJECT (COMBO, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (COMBO, image30, "image30");
  GLADE_HOOKUP_OBJECT (COMBO, button48, "button48");
  GLADE_HOOKUP_OBJECT (COMBO, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (COMBO, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (COMBO, image17, "image17");
  GLADE_HOOKUP_OBJECT (COMBO, label83, "label83");
  GLADE_HOOKUP_OBJECT (COMBO, button49, "button49");
  GLADE_HOOKUP_OBJECT (COMBO, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (COMBO, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (COMBO, image22, "image22");
  GLADE_HOOKUP_OBJECT (COMBO, label88, "label88");
  GLADE_HOOKUP_OBJECT (COMBO, button50, "button50");
  GLADE_HOOKUP_OBJECT (COMBO, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (COMBO, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (COMBO, image20, "image20");
  GLADE_HOOKUP_OBJECT (COMBO, label87, "label87");
  GLADE_HOOKUP_OBJECT (COMBO, button51, "button51");
  GLADE_HOOKUP_OBJECT (COMBO, image21, "image21");
  GLADE_HOOKUP_OBJECT (COMBO, label80, "label80");
  GLADE_HOOKUP_OBJECT (COMBO, label78, "label78");
  GLADE_HOOKUP_OBJECT (COMBO, label77, "label77");
  GLADE_HOOKUP_OBJECT (COMBO, label81, "label81");
  GLADE_HOOKUP_OBJECT (COMBO, label82, "label82");
  GLADE_HOOKUP_OBJECT (COMBO, label84, "label84");
  GLADE_HOOKUP_OBJECT (COMBO, label85, "label85");
  GLADE_HOOKUP_OBJECT (COMBO, label79, "label79");
  GLADE_HOOKUP_OBJECT (COMBO, label76, "label76");

  return COMBO;
}

