/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_des_services (void)
{
  GtkWidget *Gestion_des_services;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *ctree1;
  GtkWidget *ID;
  GtkWidget *Nom_de_Service;
  GtkWidget *Description;
  GtkWidget *Prix;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *image20;
  GtkWidget *button5;
  GtkWidget *alignment19;
  GtkWidget *hbox29;
  GtkWidget *image21;
  GtkWidget *label43;
  GtkWidget *button7;
  GtkWidget *alignment24;
  GtkWidget *hbox34;
  GtkWidget *image26;
  GtkWidget *label48;
  GtkWidget *button8;
  GtkWidget *alignment23;
  GtkWidget *hbox33;
  GtkWidget *image25;
  GtkWidget *label47;
  GtkWidget *button9;
  GtkWidget *alignment22;
  GtkWidget *hbox32;
  GtkWidget *image24;
  GtkWidget *label46;
  GtkWidget *button10;
  GtkWidget *alignment21;
  GtkWidget *hbox31;
  GtkWidget *image23;
  GtkWidget *label45;
  GtkWidget *button6;
  GtkWidget *alignment20;
  GtkWidget *hbox30;
  GtkWidget *image22;
  GtkWidget *label44;
  GtkWidget *Prix;
  GtkWidget *Description;
  GtkWidget *Nom_de_Service;
  GtkWidget *Gestion_des_services;
  GtkWidget *fixed3;
  GtkWidget *ctree2;
  GtkWidget *ID_;
  GtkWidget *Nom_de_Service;
  GtkWidget *image17;
  GtkWidget *button4;
  GtkWidget *alignment17;
  GtkWidget *hbox27;
  GtkWidget *image18;
  GtkWidget *label41;
  GtkWidget *button3;
  GtkWidget *alignment18;
  GtkWidget *hbox28;
  GtkWidget *image19;
  GtkWidget *label42;
  GtkWidget *label20;
  GtkWidget *combo1;
  GtkWidget *combo_entry1;
  GtkWidget *Affectation_de_service____une_reservation;
  GtkWidget *fixed4;
  GtkWidget *ctree4;
  GtkWidget *Date;
  GtkWidget *Action;
  GtkWidget *Service;
  GtkWidget *textview1;
  GtkWidget *image28;
  GtkWidget *button11;
  GtkWidget *alignment25;
  GtkWidget *hbox35;
  GtkWidget *image27;
  GtkWidget *label49;
  GtkWidget *Historique_des_Modifications;
  GtkWidget *empty_notebook_page;
  GtkWidget *label21;
  GtkWidget *label22;

  Gestion_des_services = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_des_services, 1060, 663);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_services), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (Gestion_des_services), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Gestion_des_services), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 8, 0);
  gtk_widget_set_size_request (notebook1, 1060, 663);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  ctree1 = gtk_ctree_new (4, 0);
  gtk_widget_show (ctree1);
  gtk_fixed_put (GTK_FIXED (fixed2), ctree1, 8, 16);
  gtk_widget_set_size_request (ctree1, 900, 287);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 0, 137);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 1, 255);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 2, 305);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree1));

  ID = gtk_label_new (_("ID"));
  gtk_widget_show (ID);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 0, ID);

  Nom_de_Service = gtk_label_new (_("Nom de Service"));
  gtk_widget_show (Nom_de_Service);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 1, Nom_de_Service);

  Description = gtk_label_new (_("Description "));
  gtk_widget_show (Description);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 2, Description);

  Prix = gtk_label_new (_("Prix"));
  gtk_widget_show (Prix);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 3, Prix);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 144, 384);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 144, 432);
  gtk_widget_set_size_request (entry2, 160, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 144, 504);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  image20 = create_pixmap (Gestion_des_services, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed2), image20, 0, 0);
  gtk_widget_set_size_request (image20, 1060, 663);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 927, 584);
  gtk_widget_set_size_request (button5, 109, 35);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button5), alignment19);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox29);

  image21 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox29), image21, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox29), label43, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 327, 328);
  gtk_widget_set_size_request (button7, 109, 35);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button7), alignment24);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox34);

  image26 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox34), image26, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox34), label48, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 220, 328);
  gtk_widget_set_size_request (button8, 109, 35);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button8), alignment23);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox33);

  image25 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox33), image25, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox33), label47, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed2), button9, 112, 328);
  gtk_widget_set_size_request (button9, 109, 35);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button9), alignment22);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox32);

  image24 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox32), image24, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox32), label46, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed2), button10, 13, 328);
  gtk_widget_set_size_request (button10, 109, 35);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button10), alignment21);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox31);

  image23 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox31), image23, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox31), label45, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 48, 560);
  gtk_widget_set_size_request (button6, 109, 35);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button6), alignment20);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox30);

  image22 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox30), image22, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox30), label44, FALSE, FALSE, 0);

  Prix = gtk_label_new (_("Prix:"));
  gtk_widget_show (Prix);
  gtk_fixed_put (GTK_FIXED (fixed2), Prix, 0, 504);
  gtk_widget_set_size_request (Prix, 56, 32);

  Description = gtk_label_new (_("Description :"));
  gtk_widget_show (Description);
  gtk_fixed_put (GTK_FIXED (fixed2), Description, 8, 431);
  gtk_widget_set_size_request (Description, 96, 24);

  Nom_de_Service = gtk_label_new (_("Nom de Service :"));
  gtk_widget_show (Nom_de_Service);
  gtk_fixed_put (GTK_FIXED (fixed2), Nom_de_Service, 8, 376);
  gtk_widget_set_size_request (Nom_de_Service, 128, 40);

  Gestion_des_services = gtk_label_new (_("Gestion des Services"));
  gtk_widget_show (Gestion_des_services);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Gestion_des_services);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  ctree2 = gtk_ctree_new (2, 0);
  gtk_widget_show (ctree2);
  gtk_fixed_put (GTK_FIXED (fixed3), ctree2, 48, 168);
  gtk_widget_set_size_request (ctree2, 437, 303);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 0, 143);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree2));

  ID_ = gtk_label_new (_("ID"));
  gtk_widget_show (ID_);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 0, ID_);

  Nom_de_Service = gtk_label_new (_("Nom de service"));
  gtk_widget_show (Nom_de_Service);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 1, Nom_de_Service);

  image17 = create_pixmap (Gestion_des_services, "fotor-2024101822257.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed3), image17, 0, 0);
  gtk_widget_set_size_request (image17, 1060, 663);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 927, 584);
  gtk_widget_set_size_request (button4, 109, 35);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button4), alignment17);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox27);

  image18 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox27), image18, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox27), label41, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 88, 504);
  gtk_widget_set_size_request (button3, 109, 35);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button3), alignment18);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox28);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox28), image19, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox28), label42, FALSE, FALSE, 0);

  label20 = gtk_label_new (_("S\303\251lectionnez une r\303\251servation :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 0, 64);
  gtk_widget_set_size_request (label20, 267, 60);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed3), combo1, 255, 58);
  gtk_widget_set_size_request (combo1, 336, 79);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (combo_entry1);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry1), 8226);

  Affectation_de_service____une_reservation = gtk_label_new (_("Affectation de Service \303\240 une Reservation"));
  gtk_widget_show (Affectation_de_service____une_reservation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), Affectation_de_service____une_reservation);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  ctree4 = gtk_ctree_new (3, 0);
  gtk_widget_show (ctree4);
  gtk_fixed_put (GTK_FIXED (fixed4), ctree4, 32, 24);
  gtk_widget_set_size_request (ctree4, 748, 391);
  gtk_clist_set_column_width (GTK_CLIST (ctree4), 0, 152);
  gtk_clist_set_column_width (GTK_CLIST (ctree4), 1, 306);
  gtk_clist_set_column_width (GTK_CLIST (ctree4), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree4));

  Date = gtk_label_new (_("Date"));
  gtk_widget_show (Date);
  gtk_clist_set_column_widget (GTK_CLIST (ctree4), 0, Date);

  Action = gtk_label_new (_("Action"));
  gtk_widget_show (Action);
  gtk_clist_set_column_widget (GTK_CLIST (ctree4), 1, Action);

  Service = gtk_label_new (_("Service"));
  gtk_widget_show (Service);
  gtk_clist_set_column_widget (GTK_CLIST (ctree4), 2, Service);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed4), textview1, 32, 464);
  gtk_widget_set_size_request (textview1, 748, 133);

  image28 = create_pixmap (Gestion_des_services, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed4), image28, 0, 0);
  gtk_widget_set_size_request (image28, 1060, 663);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 927, 584);
  gtk_widget_set_size_request (button11, 109, 35);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button11), alignment25);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox35);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox35), image27, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox35), label49, FALSE, FALSE, 0);

  Historique_des_Modifications = gtk_label_new (_("Historique des Modifications"));
  gtk_widget_show (Historique_des_Modifications);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), Historique_des_Modifications);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label21);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label22 = gtk_label_new ("");
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label22);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_services, Gestion_des_services, "Gestion_des_services");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, ctree1, "ctree1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, ID, "ID");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Nom_de_Service, "Nom_de_Service");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Description, "Description");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Prix, "Prix");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button5, "button5");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button7, "button7");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image26, "image26");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label48, "label48");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button8, "button8");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image25, "image25");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label47, "label47");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button9, "button9");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image24, "image24");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label46, "label46");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button10, "button10");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image23, "image23");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label45, "label45");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button6, "button6");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image22, "image22");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label44, "label44");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Prix, "Prix");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Description, "Description");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Nom_de_Service, "Nom_de_Service");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Gestion_des_services, "Gestion_des_services");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, ctree2, "ctree2");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, ID_, "ID_");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Nom_de_Service, "Nom_de_Service");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image17, "image17");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button4, "button4");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image18, "image18");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button3, "button3");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label42, "label42");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label20, "label20");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Affectation_de_service____une_reservation, "Affectation_de_service____une_reservation");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, ctree4, "ctree4");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Date, "Date");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Action, "Action");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Service, "Service");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image28, "image28");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, button11, "button11");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, image27, "image27");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label49, "label49");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, Historique_des_Modifications, "Historique_des_Modifications");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label21, "label21");
  GLADE_HOOKUP_OBJECT (Gestion_des_services, label22, "label22");

  return Gestion_des_services;
}

GtkWidget*
create___tes__vous_s__r_e___ (void)
{
  GtkWidget *__tes__vous_s__r_e___;
  GtkWidget *fixed5;
  GtkWidget *label38;
  GtkWidget *button1;
  GtkWidget *alignment15;
  GtkWidget *hbox25;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *button2;
  GtkWidget *alignment16;
  GtkWidget *hbox26;
  GtkWidget *image16;
  GtkWidget *label40;

  __tes__vous_s__r_e___ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (__tes__vous_s__r_e___, 400, 150);
  gtk_window_set_title (GTK_WINDOW (__tes__vous_s__r_e___), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (__tes__vous_s__r_e___), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (__tes__vous_s__r_e___), fixed5);

  label38 = gtk_label_new (_("\303\212tes- vous s\303\273r(e) ?"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 128, 32);
  gtk_widget_set_size_request (label38, 135, 17);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed5), button1, 104, 88);
  gtk_widget_set_size_request (button1, 74, 33);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button1), alignment15);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox25);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox25), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox25), label39, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed5), button2, 224, 88);
  gtk_widget_set_size_request (button2, 66, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button2), alignment16);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox26);

  image16 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox26), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox26), label40, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (__tes__vous_s__r_e___, __tes__vous_s__r_e___, "__tes__vous_s__r_e___");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, label38, "label38");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, button1, "button1");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, image15, "image15");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, label39, "label39");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, button2, "button2");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, image16, "image16");
  GLADE_HOOKUP_OBJECT (__tes__vous_s__r_e___, label40, "label40");

  return __tes__vous_s__r_e___;
}

