/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed10;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkWidget *entry23;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *entry26;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *combo14;
  GtkWidget *combo_entry12;
  GtkWidget *combo11;
  GList *combo11_items = NULL;
  GtkWidget *combo_entry9;
  GtkWidget *combo12;
  GList *combo12_items = NULL;
  GtkWidget *combo_entry10;
  GtkWidget *combo13;
  GList *combo13_items = NULL;
  GtkWidget *combo_entry11;
  GtkWidget *image16;
  GtkWidget *button17;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image27;
  GtkWidget *label104;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *label76;
  GtkWidget *filechooserbutton1;
  GtkWidget *label99;
  GtkWidget *label73;
  GtkWidget *label72;
  GtkWidget *label71;
  GtkWidget *label70;
  GtkWidget *label69;
  GtkWidget *label68;
  GtkWidget *label67;
  GtkWidget *label66;
  GtkWidget *label75;
  GtkWidget *label74;
  GtkWidget *label1;
  GtkWidget *fixed4;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *image6;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label36;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkWidget *label33;
  GtkWidget *label32;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label47;
  GtkWidget *combo10;
  GList *combo10_items = NULL;
  GtkWidget *entry14;
  GtkWidget *combo9;
  GList *combo9_items = NULL;
  GtkWidget *entry13;
  GtkWidget *combo6;
  GList *combo6_items = NULL;
  GtkWidget *combo_entry6;
  GtkWidget *combo8;
  GtkWidget *combo_entry8;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label46;
  GtkWidget *label42;
  GtkWidget *label100;
  GtkWidget *filechooserbutton2;
  GtkWidget *button3;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image26;
  GtkWidget *label103;
  GtkWidget *label2;
  GtkWidget *fixed5;
  GtkWidget *entry20;
  GtkWidget *image19;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label50;
  GtkWidget *button4;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image25;
  GtkWidget *label102;
  GtkWidget *label49;
  GtkWidget *label3;
  GtkWidget *fixed6;
  GtkWidget *ctree5;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label113;
  GtkWidget *image29;
  GtkWidget *button16;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image24;
  GtkWidget *label101;
  GtkWidget *button18;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label105;
  GtkWidget *label4;
  GtkWidget *fixed7;
  GtkWidget *ctree3;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label92;
  GtkWidget *image30;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image21;
  GtkWidget *label96;
  GtkWidget *combo15;
  GList *combo15_items = NULL;
  GtkWidget *combo_entry13;
  GtkWidget *combo16;
  GList *combo16_items = NULL;
  GtkWidget *combo_entry14;
  GtkWidget *label83;
  GtkWidget *combo17;
  GtkWidget *combo_entry15;
  GtkWidget *button19;
  GtkWidget *image31;
  GtkWidget *label5;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window, 1060, 663);
  gtk_window_set_title (GTK_WINDOW (window), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (window), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1060, 663);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed10), entry21, 237, 39);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed10), entry22, 237, 94);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  entry23 = gtk_entry_new ();
  gtk_widget_show (entry23);
  gtk_fixed_put (GTK_FIXED (fixed10), entry23, 237, 151);
  gtk_widget_set_size_request (entry23, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed10), entry24, 784, 39);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed10), entry25, 784, 95);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed10), entry26, 784, 151);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed10), entry27, 784, 206);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed10), entry28, 784, 270);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  combo14 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo14)->popwin),
                     "GladeParentKey", combo14);
  gtk_widget_show (combo14);
  gtk_fixed_put (GTK_FIXED (fixed10), combo14, 413, 271);
  gtk_widget_set_size_request (combo14, 92, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo14), TRUE);

  combo_entry12 = GTK_COMBO (combo14)->entry;
  gtk_widget_show (combo_entry12);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry12), 8226);

  combo11 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo11)->popwin),
                     "GladeParentKey", combo11);
  gtk_widget_show (combo11);
  gtk_fixed_put (GTK_FIXED (fixed10), combo11, 237, 207);
  gtk_widget_set_size_request (combo11, 161, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo11), TRUE);
  combo11_items = g_list_append (combo11_items, (gpointer) _("Femme"));
  combo11_items = g_list_append (combo11_items, (gpointer) _("Homme"));
  combo11_items = g_list_append (combo11_items, (gpointer) _("Personnalis\303\251"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo11), combo11_items);
  g_list_free (combo11_items);

  combo_entry9 = GTK_COMBO (combo11)->entry;
  gtk_widget_show (combo_entry9);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry9), 8226);

  combo12 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo12)->popwin),
                     "GladeParentKey", combo12);
  gtk_widget_show (combo12);
  gtk_fixed_put (GTK_FIXED (fixed10), combo12, 237, 271);
  gtk_widget_set_size_request (combo12, 71, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo12), TRUE);
  combo12_items = g_list_append (combo12_items, (gpointer) "");
  combo12_items = g_list_append (combo12_items, (gpointer) _("1"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("2"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("3"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("4"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("6"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("7"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("8"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("9"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("10"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("11"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("12"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("13"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("14"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("15"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("16"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("17"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("18"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("19"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("20"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("21"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("22"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("23"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("24"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("25"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("26"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("27"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("28"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("29"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("30"));
  combo12_items = g_list_append (combo12_items, (gpointer) _("31"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo12), combo12_items);
  g_list_free (combo12_items);

  combo_entry10 = GTK_COMBO (combo12)->entry;
  gtk_widget_show (combo_entry10);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry10), 8226);

  combo13 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo13)->popwin),
                     "GladeParentKey", combo13);
  gtk_widget_show (combo13);
  gtk_fixed_put (GTK_FIXED (fixed10), combo13, 307, 271);
  gtk_widget_set_size_request (combo13, 110, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo13), TRUE);
  combo13_items = g_list_append (combo13_items, (gpointer) "");
  combo13_items = g_list_append (combo13_items, (gpointer) _("Janvier"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("F\303\251vrier"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Mars"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Avril"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Mai"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Juin"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Juillet"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Septembre"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Octobre"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("Novembre"));
  combo13_items = g_list_append (combo13_items, (gpointer) _("D\303\251cembre"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo13), combo13_items);
  g_list_free (combo13_items);

  combo_entry11 = GTK_COMBO (combo13)->entry;
  gtk_widget_show (combo_entry11);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry11), 8226);

  image16 = create_pixmap (window, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jpg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed10), image16, 0, 0);
  gtk_widget_set_size_request (image16, 1060, 663);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed10), button17, 927, 584);
  gtk_widget_set_size_request (button17, 109, 35);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button17), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image27 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox16), image27, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox16), label104, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed10), button11, 496, 416);
  gtk_widget_set_size_request (button11, 109, 35);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox11), label76, FALSE, FALSE, 0);

  filechooserbutton1 = gtk_file_chooser_button_new (_("S\303\251lectionner un fichier"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton1);
  gtk_fixed_put (GTK_FIXED (fixed10), filechooserbutton1, 784, 320);
  gtk_widget_set_size_request (filechooserbutton1, 160, 29);

  label99 = gtk_label_new (_("Uploadez votre photo  :"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed10), label99, 600, 328);
  gtk_widget_set_size_request (label99, 171, 17);

  label73 = gtk_label_new (_("Email :"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed10), label73, 649, 150);
  gtk_widget_set_size_request (label73, 72, 25);

  label72 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed10), label72, 647, 98);
  gtk_widget_set_size_request (label72, 75, 17);

  label71 = gtk_label_new (_("N\302\260 de t\303\251l\303\251phone :"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed10), label71, 632, 43);
  gtk_widget_set_size_request (label71, 121, 17);

  label70 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed10), label70, 76, 274);
  gtk_widget_set_size_request (label70, 137, 17);

  label69 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed10), label69, 96, 214);
  gtk_widget_set_size_request (label69, 49, 17);

  label68 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed10), label68, 88, 160);
  gtk_widget_set_size_request (label68, 89, 17);

  label67 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed10), label67, 93, 99);
  gtk_widget_set_size_request (label67, 69, 17);

  label66 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed10), label66, 96, 43);
  gtk_widget_set_size_request (label66, 49, 17);

  label75 = gtk_label_new (_("ID-Parking  :"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed10), label75, 613, 274);
  gtk_widget_set_size_request (label75, 148, 17);

  label74 = gtk_label_new (_("R\303\264le :"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed10), label74, 650, 207);
  gtk_widget_set_size_request (label74, 73, 25);

  label1 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_widget_set_size_request (label1, 64, 22);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10, 328, 29);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11, 184, 104);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 192, 176);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15, 736, 96);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed4), entry16, 736, 312);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed4), entry17, 736, 168);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed4), entry18, 736, 240);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed4), entry19, 736, 384);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  image6 = create_pixmap (window, "WhatsApp Image 2024-10-15 at 21.07.31-fotor-20241017222649.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed4), image6, 0, 0);
  gtk_widget_set_size_request (image6, 1060, 663);

  label41 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed4), label41, 576, 320);
  gtk_widget_set_size_request (label41, 79, 17);

  label40 = gtk_label_new (_("Email : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed4), label40, 592, 248);
  gtk_widget_set_size_request (label40, 49, 17);

  label38 = gtk_label_new (_("R\303\264le : "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed4), label38, 590, 176);
  gtk_widget_set_size_request (label38, 49, 17);

  label39 = gtk_label_new (_("N\302\260 de t\303\251l\303\251phone :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed4), label39, 560, 104);
  gtk_widget_set_size_request (label39, 142, 17);

  label36 = gtk_label_new (_("Date de naissance : "));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 48, 328);
  gtk_widget_set_size_request (label36, 142, 17);

  label35 = gtk_label_new (_("Sexe : "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 96, 256);
  gtk_widget_set_size_request (label35, 49, 17);

  label34 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 96, 184);
  gtk_widget_set_size_request (label34, 67, 17);

  label33 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 96, 112);
  gtk_widget_set_size_request (label33, 53, 16);

  label32 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 224, 37);
  gtk_widget_set_size_request (label32, 97, 17);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 744, 24);
  gtk_widget_set_size_request (button6, 109, 35);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox6), label47, FALSE, FALSE, 0);

  combo10 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo10)->popwin),
                     "GladeParentKey", combo10);
  gtk_widget_show (combo10);
  gtk_fixed_put (GTK_FIXED (fixed4), combo10, 260, 320);
  gtk_widget_set_size_request (combo10, 114, 27);
  GTK_WIDGET_SET_FLAGS (combo10, GTK_CAN_FOCUS);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo10), TRUE);
  combo10_items = g_list_append (combo10_items, (gpointer) "");
  combo10_items = g_list_append (combo10_items, (gpointer) _("Janvier"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("F\303\251vrier"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Mars"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Avril"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Mai"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Juin"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Juillet"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Septembre"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Octobre"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("Novembre"));
  combo10_items = g_list_append (combo10_items, (gpointer) _("D\303\251cembre"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo10), combo10_items);
  g_list_free (combo10_items);

  entry14 = GTK_COMBO (combo10)->entry;
  gtk_widget_show (entry14);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  combo9 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo9)->popwin),
                     "GladeParentKey", combo9);
  gtk_widget_show (combo9);
  gtk_fixed_put (GTK_FIXED (fixed4), combo9, 191, 320);
  gtk_widget_set_size_request (combo9, 71, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo9), TRUE);
  combo9_items = g_list_append (combo9_items, (gpointer) "");
  combo9_items = g_list_append (combo9_items, (gpointer) _("1"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("2"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("3"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("4"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("6"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("7"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("8"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("9"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("10"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("11"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("12"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("13"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("14"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("15"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("16"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("17"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("18"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("19"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("20"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("21"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("22"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("23"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("24"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("25"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("26"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("27"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("28"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("29"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("30"));
  combo9_items = g_list_append (combo9_items, (gpointer) _("31"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo9), combo9_items);
  g_list_free (combo9_items);

  entry13 = GTK_COMBO (combo9)->entry;
  gtk_widget_show (entry13);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  combo6 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo6)->popwin),
                     "GladeParentKey", combo6);
  gtk_widget_show (combo6);
  gtk_fixed_put (GTK_FIXED (fixed4), combo6, 192, 248);
  gtk_widget_set_size_request (combo6, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo6), TRUE);
  combo6_items = g_list_append (combo6_items, (gpointer) "");
  combo6_items = g_list_append (combo6_items, (gpointer) _("Femme"));
  combo6_items = g_list_append (combo6_items, (gpointer) _("Homme"));
  combo6_items = g_list_append (combo6_items, (gpointer) _("Personnalis\303\251"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo6), combo6_items);
  g_list_free (combo6_items);

  combo_entry6 = GTK_COMBO (combo6)->entry;
  gtk_widget_show (combo_entry6);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry6), 8226);

  combo8 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo8)->popwin),
                     "GladeParentKey", combo8);
  gtk_widget_show (combo8);
  gtk_fixed_put (GTK_FIXED (fixed4), combo8, 372, 320);
  gtk_widget_set_size_request (combo8, 88, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo8), TRUE);

  combo_entry8 = GTK_COMBO (combo8)->entry;
  gtk_widget_show (combo_entry8);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry8), 8226);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 568, 24);
  gtk_widget_set_size_request (button5, 165, 35);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Afficher les donn\303\251es"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox5), label46, FALSE, FALSE, 0);

  label42 = gtk_label_new (_("ID-Parking : "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed4), label42, 542, 392);
  gtk_widget_set_size_request (label42, 160, 17);

  label100 = gtk_label_new (_("Uploadez votre image : "));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed4), label100, 51, 389);
  gtk_widget_set_size_request (label100, 169, 17);

  filechooserbutton2 = gtk_file_chooser_button_new (_("S\303\251lectionner un fichier"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), filechooserbutton2, 255, 381);
  gtk_widget_set_size_request (filechooserbutton2, 160, 29);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 927, 584);
  gtk_widget_set_size_request (button3, 109, 35);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button3), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image26 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox15), image26, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox15), label103, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_widget_set_size_request (label2, 62, -1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed5), entry20, 528, 216);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  image19 = create_pixmap (window, "WhatsApp Image 2024-10-15 at 21.07.31-fotor-2024101824253.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed5), image19, 0, 0);
  gtk_widget_set_size_request (image19, 1060, 663);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 448, 296);
  gtk_widget_set_size_request (button7, 107, 35);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox7), label50, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed5), button4, 927, 584);
  gtk_widget_set_size_request (button4, 109, 35);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button4), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image25 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox14), image25, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox14), label102, FALSE, FALSE, 0);

  label49 = gtk_label_new (_("Identifiant : "));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 328, 221);
  gtk_widget_set_size_request (label49, 103, 17);

  label3 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  ctree5 = gtk_ctree_new (8, 0);
  gtk_widget_show (ctree5);
  gtk_fixed_put (GTK_FIXED (fixed6), ctree5, 96, 72);
  gtk_widget_set_size_request (ctree5, 858, 458);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 2, 86);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 3, 105);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 4, 102);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 5, 112);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 6, 120);
  gtk_clist_set_column_width (GTK_CLIST (ctree5), 7, 95);
  gtk_clist_column_titles_show (GTK_CLIST (ctree5));

  label106 = gtk_label_new (_("Nom"));
  gtk_widget_show (label106);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 0, label106);

  label107 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label107);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 1, label107);

  label108 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label108);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 2, label108);

  label109 = gtk_label_new (_("R\303\264le"));
  gtk_widget_show (label109);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 3, label109);

  label110 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label110);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 4, label110);

  label111 = gtk_label_new (_("E-mail"));
  gtk_widget_show (label111);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 5, label111);

  label112 = gtk_label_new (_("N\302\260 de t\303\251l\303\251phone"));
  gtk_widget_show (label112);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 6, label112);

  label113 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label113);
  gtk_clist_set_column_widget (GTK_CLIST (ctree5), 7, label113);

  image29 = create_pixmap (window, "0815bae3-ee8b-45e0-bc27-2e0d0d0d7094 (1).jfif");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed6), image29, 0, 0);
  gtk_widget_set_size_request (image29, 1060, 663);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed6), button16, 927, 584);
  gtk_widget_set_size_request (button16, 109, 35);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button16), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox13), image24, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox13), label101, FALSE, FALSE, 0);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed6), button18, 152, 24);
  gtk_widget_set_size_request (button18, 109, 35);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button18), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox17), label105, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_widget_set_size_request (label4, 63, -1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  ctree3 = gtk_ctree_new (9, 0);
  gtk_widget_show (ctree3);
  gtk_fixed_put (GTK_FIXED (fixed7), ctree3, 80, 152);
  gtk_widget_set_size_request (ctree3, 810, 424);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 0, 84);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 3, 90);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 5, 78);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 6, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 7, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree3), 8, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree3));

  label84 = gtk_label_new (_("ID-Parking"));
  gtk_widget_show (label84);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 0, label84);

  label85 = gtk_label_new (_("Nom"));
  gtk_widget_show (label85);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 1, label85);

  label86 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label86);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 2, label86);

  label87 = gtk_label_new (_("CIN"));
  gtk_widget_show (label87);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 3, label87);

  label88 = gtk_label_new (_("N\302\260 de t\303\251l"));
  gtk_widget_show (label88);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 4, label88);

  label89 = gtk_label_new (_("Heure"));
  gtk_widget_show (label89);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 5, label89);

  label90 = gtk_label_new (_("Dur\303\251e"));
  gtk_widget_show (label90);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 6, label90);

  label91 = gtk_label_new (_("ID-VEH"));
  gtk_widget_show (label91);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 7, label91);

  label92 = gtk_label_new (_("Place"));
  gtk_widget_show (label92);
  gtk_clist_set_column_widget (GTK_CLIST (ctree3), 8, label92);

  image30 = create_pixmap (window, "WhatsApp Image 2024-10-15 at 21.07.31-fotor-2024101825825.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed7), image30, 0, 0);
  gtk_widget_set_size_request (image30, 1060, 663);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed7), button12, 927, 584);
  gtk_widget_set_size_request (button12, 109, 35);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image21 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox12), image21, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox12), label96, FALSE, FALSE, 0);

  combo15 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo15)->popwin),
                     "GladeParentKey", combo15);
  gtk_widget_show (combo15);
  gtk_fixed_put (GTK_FIXED (fixed7), combo15, 272, 64);
  gtk_widget_set_size_request (combo15, 66, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo15), TRUE);
  combo15_items = g_list_append (combo15_items, (gpointer) "");
  combo15_items = g_list_append (combo15_items, (gpointer) _("1"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("2"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("3"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("4"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("6"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("7"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("8"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("9"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("10"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("11"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("12"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("13"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("14"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("15"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("16"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("17"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("18"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("19"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("20"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("21"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("22"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("23"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("24"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("25"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("26"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("27"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("28"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("29"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("30"));
  combo15_items = g_list_append (combo15_items, (gpointer) _("31"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo15), combo15_items);
  g_list_free (combo15_items);

  combo_entry13 = GTK_COMBO (combo15)->entry;
  gtk_widget_show (combo_entry13);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry13), 8226);

  combo16 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo16)->popwin),
                     "GladeParentKey", combo16);
  gtk_widget_show (combo16);
  gtk_fixed_put (GTK_FIXED (fixed7), combo16, 336, 64);
  gtk_widget_set_size_request (combo16, 131, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo16), TRUE);
  combo16_items = g_list_append (combo16_items, (gpointer) "");
  combo16_items = g_list_append (combo16_items, (gpointer) _("Janvier"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("F\303\251vrier"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Mars"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Avril"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Mai"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Juin"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Juillet"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Septembre"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Octobre"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("Novembre"));
  combo16_items = g_list_append (combo16_items, (gpointer) _("D\303\251cembre"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo16), combo16_items);
  g_list_free (combo16_items);

  combo_entry14 = GTK_COMBO (combo16)->entry;
  gtk_widget_show (combo_entry14);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry14), 8226);

  label83 = gtk_label_new (_("S\303\251l\303\251ctionnez une date :"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed7), label83, 104, 72);
  gtk_widget_set_size_request (label83, 171, 17);

  combo17 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo17)->popwin),
                     "GladeParentKey", combo17);
  gtk_widget_show (combo17);
  gtk_fixed_put (GTK_FIXED (fixed7), combo17, 464, 64);
  gtk_widget_set_size_request (combo17, 115, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo17), TRUE);

  combo_entry15 = GTK_COMBO (combo17)->entry;
  gtk_widget_show (combo_entry15);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry15), 8226);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed7), button19, 586, 64);
  gtk_widget_set_size_request (button19, 49, 27);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (button19), image31);
  gtk_widget_set_size_request (image31, 13, 16);

  label5 = gtk_label_new (_("R\303\251servations"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (window, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (window, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (window, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (window, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (window, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (window, combo14, "combo14");
  GLADE_HOOKUP_OBJECT (window, combo_entry12, "combo_entry12");
  GLADE_HOOKUP_OBJECT (window, combo11, "combo11");
  GLADE_HOOKUP_OBJECT (window, combo_entry9, "combo_entry9");
  GLADE_HOOKUP_OBJECT (window, combo12, "combo12");
  GLADE_HOOKUP_OBJECT (window, combo_entry10, "combo_entry10");
  GLADE_HOOKUP_OBJECT (window, combo13, "combo13");
  GLADE_HOOKUP_OBJECT (window, combo_entry11, "combo_entry11");
  GLADE_HOOKUP_OBJECT (window, image16, "image16");
  GLADE_HOOKUP_OBJECT (window, button17, "button17");
  GLADE_HOOKUP_OBJECT (window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window, image27, "image27");
  GLADE_HOOKUP_OBJECT (window, label104, "label104");
  GLADE_HOOKUP_OBJECT (window, button11, "button11");
  GLADE_HOOKUP_OBJECT (window, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window, image18, "image18");
  GLADE_HOOKUP_OBJECT (window, label76, "label76");
  GLADE_HOOKUP_OBJECT (window, filechooserbutton1, "filechooserbutton1");
  GLADE_HOOKUP_OBJECT (window, label99, "label99");
  GLADE_HOOKUP_OBJECT (window, label73, "label73");
  GLADE_HOOKUP_OBJECT (window, label72, "label72");
  GLADE_HOOKUP_OBJECT (window, label71, "label71");
  GLADE_HOOKUP_OBJECT (window, label70, "label70");
  GLADE_HOOKUP_OBJECT (window, label69, "label69");
  GLADE_HOOKUP_OBJECT (window, label68, "label68");
  GLADE_HOOKUP_OBJECT (window, label67, "label67");
  GLADE_HOOKUP_OBJECT (window, label66, "label66");
  GLADE_HOOKUP_OBJECT (window, label75, "label75");
  GLADE_HOOKUP_OBJECT (window, label74, "label74");
  GLADE_HOOKUP_OBJECT (window, label1, "label1");
  GLADE_HOOKUP_OBJECT (window, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (window, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (window, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (window, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (window, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (window, image6, "image6");
  GLADE_HOOKUP_OBJECT (window, label41, "label41");
  GLADE_HOOKUP_OBJECT (window, label40, "label40");
  GLADE_HOOKUP_OBJECT (window, label38, "label38");
  GLADE_HOOKUP_OBJECT (window, label39, "label39");
  GLADE_HOOKUP_OBJECT (window, label36, "label36");
  GLADE_HOOKUP_OBJECT (window, label35, "label35");
  GLADE_HOOKUP_OBJECT (window, label34, "label34");
  GLADE_HOOKUP_OBJECT (window, label33, "label33");
  GLADE_HOOKUP_OBJECT (window, label32, "label32");
  GLADE_HOOKUP_OBJECT (window, button6, "button6");
  GLADE_HOOKUP_OBJECT (window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window, image8, "image8");
  GLADE_HOOKUP_OBJECT (window, label47, "label47");
  GLADE_HOOKUP_OBJECT (window, combo10, "combo10");
  GLADE_HOOKUP_OBJECT (window, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (window, combo9, "combo9");
  GLADE_HOOKUP_OBJECT (window, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window, combo6, "combo6");
  GLADE_HOOKUP_OBJECT (window, combo_entry6, "combo_entry6");
  GLADE_HOOKUP_OBJECT (window, combo8, "combo8");
  GLADE_HOOKUP_OBJECT (window, combo_entry8, "combo_entry8");
  GLADE_HOOKUP_OBJECT (window, button5, "button5");
  GLADE_HOOKUP_OBJECT (window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window, image7, "image7");
  GLADE_HOOKUP_OBJECT (window, label46, "label46");
  GLADE_HOOKUP_OBJECT (window, label42, "label42");
  GLADE_HOOKUP_OBJECT (window, label100, "label100");
  GLADE_HOOKUP_OBJECT (window, filechooserbutton2, "filechooserbutton2");
  GLADE_HOOKUP_OBJECT (window, button3, "button3");
  GLADE_HOOKUP_OBJECT (window, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window, image26, "image26");
  GLADE_HOOKUP_OBJECT (window, label103, "label103");
  GLADE_HOOKUP_OBJECT (window, label2, "label2");
  GLADE_HOOKUP_OBJECT (window, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (window, image19, "image19");
  GLADE_HOOKUP_OBJECT (window, button7, "button7");
  GLADE_HOOKUP_OBJECT (window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window, image10, "image10");
  GLADE_HOOKUP_OBJECT (window, label50, "label50");
  GLADE_HOOKUP_OBJECT (window, button4, "button4");
  GLADE_HOOKUP_OBJECT (window, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window, image25, "image25");
  GLADE_HOOKUP_OBJECT (window, label102, "label102");
  GLADE_HOOKUP_OBJECT (window, label49, "label49");
  GLADE_HOOKUP_OBJECT (window, label3, "label3");
  GLADE_HOOKUP_OBJECT (window, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window, ctree5, "ctree5");
  GLADE_HOOKUP_OBJECT (window, label106, "label106");
  GLADE_HOOKUP_OBJECT (window, label107, "label107");
  GLADE_HOOKUP_OBJECT (window, label108, "label108");
  GLADE_HOOKUP_OBJECT (window, label109, "label109");
  GLADE_HOOKUP_OBJECT (window, label110, "label110");
  GLADE_HOOKUP_OBJECT (window, label111, "label111");
  GLADE_HOOKUP_OBJECT (window, label112, "label112");
  GLADE_HOOKUP_OBJECT (window, label113, "label113");
  GLADE_HOOKUP_OBJECT (window, image29, "image29");
  GLADE_HOOKUP_OBJECT (window, button16, "button16");
  GLADE_HOOKUP_OBJECT (window, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window, image24, "image24");
  GLADE_HOOKUP_OBJECT (window, label101, "label101");
  GLADE_HOOKUP_OBJECT (window, button18, "button18");
  GLADE_HOOKUP_OBJECT (window, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window, image28, "image28");
  GLADE_HOOKUP_OBJECT (window, label105, "label105");
  GLADE_HOOKUP_OBJECT (window, label4, "label4");
  GLADE_HOOKUP_OBJECT (window, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window, ctree3, "ctree3");
  GLADE_HOOKUP_OBJECT (window, label84, "label84");
  GLADE_HOOKUP_OBJECT (window, label85, "label85");
  GLADE_HOOKUP_OBJECT (window, label86, "label86");
  GLADE_HOOKUP_OBJECT (window, label87, "label87");
  GLADE_HOOKUP_OBJECT (window, label88, "label88");
  GLADE_HOOKUP_OBJECT (window, label89, "label89");
  GLADE_HOOKUP_OBJECT (window, label90, "label90");
  GLADE_HOOKUP_OBJECT (window, label91, "label91");
  GLADE_HOOKUP_OBJECT (window, label92, "label92");
  GLADE_HOOKUP_OBJECT (window, image30, "image30");
  GLADE_HOOKUP_OBJECT (window, button12, "button12");
  GLADE_HOOKUP_OBJECT (window, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window, image21, "image21");
  GLADE_HOOKUP_OBJECT (window, label96, "label96");
  GLADE_HOOKUP_OBJECT (window, combo15, "combo15");
  GLADE_HOOKUP_OBJECT (window, combo_entry13, "combo_entry13");
  GLADE_HOOKUP_OBJECT (window, combo16, "combo16");
  GLADE_HOOKUP_OBJECT (window, combo_entry14, "combo_entry14");
  GLADE_HOOKUP_OBJECT (window, label83, "label83");
  GLADE_HOOKUP_OBJECT (window, combo17, "combo17");
  GLADE_HOOKUP_OBJECT (window, combo_entry15, "combo_entry15");
  GLADE_HOOKUP_OBJECT (window, button19, "button19");
  GLADE_HOOKUP_OBJECT (window, image31, "image31");
  GLADE_HOOKUP_OBJECT (window, label5, "label5");

  return window;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed8;
  GtkWidget *image9;
  GtkWidget *label48;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier, 500, 100);
  gtk_window_set_title (GTK_WINDOW (modifier), _("window2"));
  gtk_window_set_resizable (GTK_WINDOW (modifier), FALSE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (modifier), fixed8);
  gtk_widget_set_size_request (fixed8, 334, 99);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed8), image9, 320, 32);
  gtk_widget_set_size_request (image9, 30, 26);

  label48 = gtk_label_new (_("Modifi\303\251 avec succ\303\250s"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed8), label48, 152, 40);
  gtk_widget_set_size_request (label48, 151, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier, label48, "label48");

  return modifier;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed9;
  GtkWidget *label51;
  GtkWidget *image11;
  GtkWidget *button9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label53;
  GtkWidget *button8;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label54;
  GtkWidget *label52;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supprimer, 500, 176);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (supprimer), FALSE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed9);
  gtk_widget_set_size_request (fixed9, 342, 150);

  label51 = gtk_label_new (_("Les donn\303\251es vont \303\252tres supprim\303\251es d\303\251finitivement"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 56, 16);
  gtk_widget_set_size_request (label51, 356, 17);

  image11 = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed9), image11, 416, 16);
  gtk_widget_set_size_request (image11, 46, 23);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 136, 104);
  gtk_widget_set_size_request (button9, 66, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox8), label53, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed9), button8, 294, 104);
  gtk_widget_set_size_request (button8, 66, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button8), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox9), label54, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("\303\212tes-vous s\303\273r(e) ?"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed9), label52, 176, 48);
  gtk_widget_set_size_request (label52, 136, 17);
  gtk_misc_set_alignment (GTK_MISC (label52), 0.47, 0.5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (supprimer, label51, "label51");
  GLADE_HOOKUP_OBJECT (supprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer, button9, "button9");
  GLADE_HOOKUP_OBJECT (supprimer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer, label53, "label53");
  GLADE_HOOKUP_OBJECT (supprimer, button8, "button8");
  GLADE_HOOKUP_OBJECT (supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (supprimer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (supprimer, image13, "image13");
  GLADE_HOOKUP_OBJECT (supprimer, label54, "label54");
  GLADE_HOOKUP_OBJECT (supprimer, label52, "label52");

  return supprimer;
}

GtkWidget*
create_notifsupp (void)
{
  GtkWidget *notifsupp;
  GtkWidget *fixed11;
  GtkWidget *image23;
  GtkWidget *label98;

  notifsupp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (notifsupp, 500, 100);
  gtk_window_set_title (GTK_WINDOW (notifsupp), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (notifsupp), FALSE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notifsupp), fixed11);
  gtk_widget_set_size_request (fixed11, 500, -1);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed11), image23, 338, 32);
  gtk_widget_set_size_request (image23, 34, 36);

  label98 = gtk_label_new (_("Agent supprim\303\251 avec succ\303\250s"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed11), label98, 95, 43);
  gtk_widget_set_size_request (label98, 222, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (notifsupp, notifsupp, "notifsupp");
  GLADE_HOOKUP_OBJECT (notifsupp, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (notifsupp, image23, "image23");
  GLADE_HOOKUP_OBJECT (notifsupp, label98, "label98");

  return notifsupp;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button14;
  GtkWidget *button15;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog1), 5);
  gtk_window_set_role (GTK_WINDOW (filechooserdialog1), "GtkFileChooserDialog");
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button14 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button14);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button14, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  button15 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button15);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button15, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button15, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button14, "button14");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button15, "button15");

  gtk_widget_grab_default (button15);
  return filechooserdialog1;
}

